/*
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMyUnoValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtexthheinle.uno.myUno.MyUnoPackage.eINSTANCE);
		return result;
	}
}
