/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Contestations</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.Contestations#getInter_contestable <em>Inter contestable</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Contestations#getPlus4_contestable <em>Plus4 contestable</em>}</li>
 * </ul>
 *
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getContestations()
 * @model
 * @generated
 */
public interface Contestations extends EObject
{
  /**
   * Returns the value of the '<em><b>Inter contestable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inter contestable</em>' attribute.
   * @see #setInter_contestable(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getContestations_Inter_contestable()
   * @model
   * @generated
   */
  String getInter_contestable();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Contestations#getInter_contestable <em>Inter contestable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inter contestable</em>' attribute.
   * @see #getInter_contestable()
   * @generated
   */
  void setInter_contestable(String value);

  /**
   * Returns the value of the '<em><b>Plus4 contestable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Plus4 contestable</em>' attribute.
   * @see #setPlus4_contestable(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getContestations_Plus4_contestable()
   * @model
   * @generated
   */
  String getPlus4_contestable();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Contestations#getPlus4_contestable <em>Plus4 contestable</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Plus4 contestable</em>' attribute.
   * @see #getPlus4_contestable()
   * @generated
   */
  void setPlus4_contestable(String value);

} // Contestations
