/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cumul</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_plus_2 <em>Cumul plus 2</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_plus_4 <em>Cumul plus 4</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_carte_couleur <em>Cumul carte couleur</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_carte_uno <em>Cumul carte uno</em>}</li>
 * </ul>
 *
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getCumul()
 * @model
 * @generated
 */
public interface Cumul extends EObject
{
  /**
   * Returns the value of the '<em><b>Cumul plus 2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cumul plus 2</em>' attribute.
   * @see #setCumul_plus_2(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getCumul_Cumul_plus_2()
   * @model
   * @generated
   */
  String getCumul_plus_2();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_plus_2 <em>Cumul plus 2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cumul plus 2</em>' attribute.
   * @see #getCumul_plus_2()
   * @generated
   */
  void setCumul_plus_2(String value);

  /**
   * Returns the value of the '<em><b>Cumul plus 4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cumul plus 4</em>' attribute.
   * @see #setCumul_plus_4(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getCumul_Cumul_plus_4()
   * @model
   * @generated
   */
  String getCumul_plus_4();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_plus_4 <em>Cumul plus 4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cumul plus 4</em>' attribute.
   * @see #getCumul_plus_4()
   * @generated
   */
  void setCumul_plus_4(String value);

  /**
   * Returns the value of the '<em><b>Cumul carte couleur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cumul carte couleur</em>' attribute.
   * @see #setCumul_carte_couleur(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getCumul_Cumul_carte_couleur()
   * @model
   * @generated
   */
  String getCumul_carte_couleur();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_carte_couleur <em>Cumul carte couleur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cumul carte couleur</em>' attribute.
   * @see #getCumul_carte_couleur()
   * @generated
   */
  void setCumul_carte_couleur(String value);

  /**
   * Returns the value of the '<em><b>Cumul carte uno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cumul carte uno</em>' attribute.
   * @see #setCumul_carte_uno(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getCumul_Cumul_carte_uno()
   * @model
   * @generated
   */
  String getCumul_carte_uno();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_carte_uno <em>Cumul carte uno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cumul carte uno</em>' attribute.
   * @see #getCumul_carte_uno()
   * @generated
   */
  void setCumul_carte_uno(String value);

} // Cumul
