/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fin Partie</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.Fin_Partie#getVainqueur_total <em>Vainqueur total</em>}</li>
 * </ul>
 *
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getFin_Partie()
 * @model
 * @generated
 */
public interface Fin_Partie extends EObject
{
  /**
   * Returns the value of the '<em><b>Vainqueur total</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtexthheinle.uno.myUno.Vainqueur_total}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vainqueur total</em>' attribute.
   * @see org.xtexthheinle.uno.myUno.Vainqueur_total
   * @see #setVainqueur_total(Vainqueur_total)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getFin_Partie_Vainqueur_total()
   * @model
   * @generated
   */
  Vainqueur_total getVainqueur_total();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Fin_Partie#getVainqueur_total <em>Vainqueur total</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vainqueur total</em>' attribute.
   * @see org.xtexthheinle.uno.myUno.Vainqueur_total
   * @see #getVainqueur_total()
   * @generated
   */
  void setVainqueur_total(Vainqueur_total value);

} // Fin_Partie
