/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Interception</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getInterception()
 * @model
 * @generated
 */
public enum Interception implements Enumerator
{
  /**
   * The '<em><b>Mm nb</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MM_NB_VALUE
   * @generated
   * @ordered
   */
  MM_NB(0, "mm_nb", "mm_nb"),

  /**
   * The '<em><b>Mm couleur</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MM_COULEUR_VALUE
   * @generated
   * @ordered
   */
  MM_COULEUR(1, "mm_couleur", "mm_couleur"),

  /**
   * The '<em><b>Mm nb couleur</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MM_NB_COULEUR_VALUE
   * @generated
   * @ordered
   */
  MM_NB_COULEUR(2, "mm_nb_couleur", "mm_nb_couleur");

  /**
   * The '<em><b>Mm nb</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MM_NB
   * @model name="mm_nb"
   * @generated
   * @ordered
   */
  public static final int MM_NB_VALUE = 0;

  /**
   * The '<em><b>Mm couleur</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MM_COULEUR
   * @model name="mm_couleur"
   * @generated
   * @ordered
   */
  public static final int MM_COULEUR_VALUE = 1;

  /**
   * The '<em><b>Mm nb couleur</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MM_NB_COULEUR
   * @model name="mm_nb_couleur"
   * @generated
   * @ordered
   */
  public static final int MM_NB_COULEUR_VALUE = 2;

  /**
   * An array of all the '<em><b>Interception</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Interception[] VALUES_ARRAY =
    new Interception[]
    {
      MM_NB,
      MM_COULEUR,
      MM_NB_COULEUR,
    };

  /**
   * A public read-only list of all the '<em><b>Interception</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Interception> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Interception</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Interception get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Interception result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Interception</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Interception getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Interception result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Interception</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Interception get(int value)
  {
    switch (value)
    {
      case MM_NB_VALUE: return MM_NB;
      case MM_COULEUR_VALUE: return MM_COULEUR;
      case MM_NB_COULEUR_VALUE: return MM_NB_COULEUR;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Interception(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Interception
