/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Inversion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.Inversion#getAvec_carte_inversion <em>Avec carte inversion</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Inversion#getAvec_carte_sept <em>Avec carte sept</em>}</li>
 * </ul>
 *
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getInversion()
 * @model
 * @generated
 */
public interface Inversion extends EObject
{
  /**
   * Returns the value of the '<em><b>Avec carte inversion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Avec carte inversion</em>' attribute.
   * @see #setAvec_carte_inversion(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getInversion_Avec_carte_inversion()
   * @model
   * @generated
   */
  String getAvec_carte_inversion();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Inversion#getAvec_carte_inversion <em>Avec carte inversion</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Avec carte inversion</em>' attribute.
   * @see #getAvec_carte_inversion()
   * @generated
   */
  void setAvec_carte_inversion(String value);

  /**
   * Returns the value of the '<em><b>Avec carte sept</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Avec carte sept</em>' attribute.
   * @see #setAvec_carte_sept(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getInversion_Avec_carte_sept()
   * @model
   * @generated
   */
  String getAvec_carte_sept();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Inversion#getAvec_carte_sept <em>Avec carte sept</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Avec carte sept</em>' attribute.
   * @see #getAvec_carte_sept()
   * @generated
   */
  void setAvec_carte_sept(String value);

} // Inversion
