/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.Main#getEtat_main <em>Etat main</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Main#getNb_mains <em>Nb mains</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Main#getNb_cartes_mains <em>Nb cartes mains</em>}</li>
 * </ul>
 *
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getMain()
 * @model
 * @generated
 */
public interface Main extends EObject
{
  /**
   * Returns the value of the '<em><b>Etat main</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtexthheinle.uno.myUno.Etat_Main}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Etat main</em>' attribute.
   * @see org.xtexthheinle.uno.myUno.Etat_Main
   * @see #setEtat_main(Etat_Main)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getMain_Etat_main()
   * @model
   * @generated
   */
  Etat_Main getEtat_main();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Main#getEtat_main <em>Etat main</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Etat main</em>' attribute.
   * @see org.xtexthheinle.uno.myUno.Etat_Main
   * @see #getEtat_main()
   * @generated
   */
  void setEtat_main(Etat_Main value);

  /**
   * Returns the value of the '<em><b>Nb mains</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtexthheinle.uno.myUno.Nb_Mains}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb mains</em>' attribute.
   * @see org.xtexthheinle.uno.myUno.Nb_Mains
   * @see #setNb_mains(Nb_Mains)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getMain_Nb_mains()
   * @model
   * @generated
   */
  Nb_Mains getNb_mains();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Main#getNb_mains <em>Nb mains</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb mains</em>' attribute.
   * @see org.xtexthheinle.uno.myUno.Nb_Mains
   * @see #getNb_mains()
   * @generated
   */
  void setNb_mains(Nb_Mains value);

  /**
   * Returns the value of the '<em><b>Nb cartes mains</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtexthheinle.uno.myUno.Nb_Cartes_Mains}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb cartes mains</em>' attribute.
   * @see org.xtexthheinle.uno.myUno.Nb_Cartes_Mains
   * @see #setNb_cartes_mains(Nb_Cartes_Mains)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getMain_Nb_cartes_mains()
   * @model
   * @generated
   */
  Nb_Cartes_Mains getNb_cartes_mains();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Main#getNb_cartes_mains <em>Nb cartes mains</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb cartes mains</em>' attribute.
   * @see org.xtexthheinle.uno.myUno.Nb_Cartes_Mains
   * @see #getNb_cartes_mains()
   * @generated
   */
  void setNb_cartes_mains(Nb_Cartes_Mains value);

} // Main
