/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Manche</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.Manche#getInversion <em>Inversion</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Manche#getTourner_les_mains <em>Tourner les mains</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Manche#getNb_cartes_jouables <em>Nb cartes jouables</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Manche#getCartes_1_9 <em>Cartes 19</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Manche#getPioche <em>Pioche</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Manche#getCumul <em>Cumul</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Manche#getContestations <em>Contestations</em>}</li>
 * </ul>
 *
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getManche()
 * @model
 * @generated
 */
public interface Manche extends EObject
{
  /**
   * Returns the value of the '<em><b>Inversion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Inversion</em>' containment reference.
   * @see #setInversion(Inversion)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getManche_Inversion()
   * @model containment="true"
   * @generated
   */
  Inversion getInversion();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Manche#getInversion <em>Inversion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Inversion</em>' containment reference.
   * @see #getInversion()
   * @generated
   */
  void setInversion(Inversion value);

  /**
   * Returns the value of the '<em><b>Tourner les mains</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tourner les mains</em>' containment reference.
   * @see #setTourner_les_mains(Tourner_les_mains)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getManche_Tourner_les_mains()
   * @model containment="true"
   * @generated
   */
  Tourner_les_mains getTourner_les_mains();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Manche#getTourner_les_mains <em>Tourner les mains</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Tourner les mains</em>' containment reference.
   * @see #getTourner_les_mains()
   * @generated
   */
  void setTourner_les_mains(Tourner_les_mains value);

  /**
   * Returns the value of the '<em><b>Nb cartes jouables</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtexthheinle.uno.myUno.Nb_cartes_jouables}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nb cartes jouables</em>' attribute.
   * @see org.xtexthheinle.uno.myUno.Nb_cartes_jouables
   * @see #setNb_cartes_jouables(Nb_cartes_jouables)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getManche_Nb_cartes_jouables()
   * @model
   * @generated
   */
  Nb_cartes_jouables getNb_cartes_jouables();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Manche#getNb_cartes_jouables <em>Nb cartes jouables</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Nb cartes jouables</em>' attribute.
   * @see org.xtexthheinle.uno.myUno.Nb_cartes_jouables
   * @see #getNb_cartes_jouables()
   * @generated
   */
  void setNb_cartes_jouables(Nb_cartes_jouables value);

  /**
   * Returns the value of the '<em><b>Cartes 19</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cartes 19</em>' containment reference.
   * @see #setCartes_1_9(Cartes_1_9)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getManche_Cartes_1_9()
   * @model containment="true"
   * @generated
   */
  Cartes_1_9 getCartes_1_9();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Manche#getCartes_1_9 <em>Cartes 19</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cartes 19</em>' containment reference.
   * @see #getCartes_1_9()
   * @generated
   */
  void setCartes_1_9(Cartes_1_9 value);

  /**
   * Returns the value of the '<em><b>Pioche</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pioche</em>' containment reference.
   * @see #setPioche(Pioche)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getManche_Pioche()
   * @model containment="true"
   * @generated
   */
  Pioche getPioche();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Manche#getPioche <em>Pioche</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pioche</em>' containment reference.
   * @see #getPioche()
   * @generated
   */
  void setPioche(Pioche value);

  /**
   * Returns the value of the '<em><b>Cumul</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cumul</em>' containment reference.
   * @see #setCumul(Cumul)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getManche_Cumul()
   * @model containment="true"
   * @generated
   */
  Cumul getCumul();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Manche#getCumul <em>Cumul</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cumul</em>' containment reference.
   * @see #getCumul()
   * @generated
   */
  void setCumul(Cumul value);

  /**
   * Returns the value of the '<em><b>Contestations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contestations</em>' containment reference.
   * @see #setContestations(Contestations)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getManche_Contestations()
   * @model containment="true"
   * @generated
   */
  Contestations getContestations();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Manche#getContestations <em>Contestations</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contestations</em>' containment reference.
   * @see #getContestations()
   * @generated
   */
  void setContestations(Contestations value);

} // Manche
