/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtexthheinle.uno.myUno.MyUnoFactory
 * @model kind="package"
 * @generated
 */
public interface MyUnoPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myUno";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtexthheinle.org/uno/MyUno";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myUno";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyUnoPackage eINSTANCE = org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.Variante_UNOImpl <em>Variante UNO</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.Variante_UNOImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getVariante_UNO()
   * @generated
   */
  int VARIANTE_UNO = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANTE_UNO__NAME = 0;

  /**
   * The feature id for the '<em><b>Configuration depart</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANTE_UNO__CONFIGURATION_DEPART = 1;

  /**
   * The feature id for the '<em><b>Manche</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANTE_UNO__MANCHE = 2;

  /**
   * The feature id for the '<em><b>Fin manche</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANTE_UNO__FIN_MANCHE = 3;

  /**
   * The feature id for the '<em><b>Fin partie</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANTE_UNO__FIN_PARTIE = 4;

  /**
   * The number of structural features of the '<em>Variante UNO</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIANTE_UNO_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.Configuration_DepartImpl <em>Configuration Depart</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.Configuration_DepartImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getConfiguration_Depart()
   * @generated
   */
  int CONFIGURATION_DEPART = 1;

  /**
   * The feature id for the '<em><b>Main</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_DEPART__MAIN = 0;

  /**
   * The feature id for the '<em><b>Talon</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_DEPART__TALON = 1;

  /**
   * The feature id for the '<em><b>Riviere</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_DEPART__RIVIERE = 2;

  /**
   * The feature id for the '<em><b>Temps limite</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_DEPART__TEMPS_LIMITE = 3;

  /**
   * The feature id for the '<em><b>Secondes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_DEPART__SECONDES = 4;

  /**
   * The number of structural features of the '<em>Configuration Depart</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONFIGURATION_DEPART_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.MainImpl <em>Main</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.MainImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getMain()
   * @generated
   */
  int MAIN = 2;

  /**
   * The feature id for the '<em><b>Etat main</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__ETAT_MAIN = 0;

  /**
   * The feature id for the '<em><b>Nb mains</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__NB_MAINS = 1;

  /**
   * The feature id for the '<em><b>Nb cartes mains</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN__NB_CARTES_MAINS = 2;

  /**
   * The number of structural features of the '<em>Main</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.TalonImpl <em>Talon</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.TalonImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getTalon()
   * @generated
   */
  int TALON = 3;

  /**
   * The feature id for the '<em><b>Nb talons</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TALON__NB_TALONS = 0;

  /**
   * The number of structural features of the '<em>Talon</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TALON_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.MancheImpl <em>Manche</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.MancheImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getManche()
   * @generated
   */
  int MANCHE = 4;

  /**
   * The feature id for the '<em><b>Inversion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANCHE__INVERSION = 0;

  /**
   * The feature id for the '<em><b>Tourner les mains</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANCHE__TOURNER_LES_MAINS = 1;

  /**
   * The feature id for the '<em><b>Nb cartes jouables</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANCHE__NB_CARTES_JOUABLES = 2;

  /**
   * The feature id for the '<em><b>Cartes 19</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANCHE__CARTES_19 = 3;

  /**
   * The feature id for the '<em><b>Pioche</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANCHE__PIOCHE = 4;

  /**
   * The feature id for the '<em><b>Cumul</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANCHE__CUMUL = 5;

  /**
   * The feature id for the '<em><b>Contestations</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANCHE__CONTESTATIONS = 6;

  /**
   * The number of structural features of the '<em>Manche</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MANCHE_FEATURE_COUNT = 7;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.InversionImpl <em>Inversion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.InversionImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getInversion()
   * @generated
   */
  int INVERSION = 5;

  /**
   * The feature id for the '<em><b>Avec carte inversion</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVERSION__AVEC_CARTE_INVERSION = 0;

  /**
   * The feature id for the '<em><b>Avec carte sept</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVERSION__AVEC_CARTE_SEPT = 1;

  /**
   * The number of structural features of the '<em>Inversion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INVERSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.Tourner_les_mainsImpl <em>Tourner les mains</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.Tourner_les_mainsImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getTourner_les_mains()
   * @generated
   */
  int TOURNER_LES_MAINS = 6;

  /**
   * The feature id for the '<em><b>Avec carte zero</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOURNER_LES_MAINS__AVEC_CARTE_ZERO = 0;

  /**
   * The feature id for the '<em><b>Avec carte uno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOURNER_LES_MAINS__AVEC_CARTE_UNO = 1;

  /**
   * The number of structural features of the '<em>Tourner les mains</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOURNER_LES_MAINS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.Cartes_1_9Impl <em>Cartes 19</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.Cartes_1_9Impl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getCartes_1_9()
   * @generated
   */
  int CARTES_19 = 7;

  /**
   * The feature id for the '<em><b>Suites</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTES_19__SUITES = 0;

  /**
   * The feature id for the '<em><b>Suites royales</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTES_19__SUITES_ROYALES = 1;

  /**
   * The feature id for the '<em><b>Interception</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTES_19__INTERCEPTION = 2;

  /**
   * The number of structural features of the '<em>Cartes 19</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTES_19_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.PiocheImpl <em>Pioche</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.PiocheImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getPioche()
   * @generated
   */
  int PIOCHE = 8;

  /**
   * The feature id for the '<em><b>Nb cartes apiocher</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIOCHE__NB_CARTES_APIOCHER = 0;

  /**
   * The feature id for the '<em><b>Jouer apres pioche</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIOCHE__JOUER_APRES_PIOCHE = 1;

  /**
   * The number of structural features of the '<em>Pioche</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PIOCHE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.CumulImpl <em>Cumul</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.CumulImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getCumul()
   * @generated
   */
  int CUMUL = 9;

  /**
   * The feature id for the '<em><b>Cumul plus 2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUMUL__CUMUL_PLUS_2 = 0;

  /**
   * The feature id for the '<em><b>Cumul plus 4</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUMUL__CUMUL_PLUS_4 = 1;

  /**
   * The feature id for the '<em><b>Cumul carte couleur</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUMUL__CUMUL_CARTE_COULEUR = 2;

  /**
   * The feature id for the '<em><b>Cumul carte uno</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUMUL__CUMUL_CARTE_UNO = 3;

  /**
   * The number of structural features of the '<em>Cumul</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUMUL_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.ContestationsImpl <em>Contestations</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.ContestationsImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getContestations()
   * @generated
   */
  int CONTESTATIONS = 10;

  /**
   * The feature id for the '<em><b>Inter contestable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTESTATIONS__INTER_CONTESTABLE = 0;

  /**
   * The feature id for the '<em><b>Plus4 contestable</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTESTATIONS__PLUS4_CONTESTABLE = 1;

  /**
   * The number of structural features of the '<em>Contestations</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTESTATIONS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.Fin_MancheImpl <em>Fin Manche</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.Fin_MancheImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getFin_Manche()
   * @generated
   */
  int FIN_MANCHE = 11;

  /**
   * The feature id for the '<em><b>Dire uno obligatoire</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIN_MANCHE__DIRE_UNO_OBLIGATOIRE = 0;

  /**
   * The feature id for the '<em><b>Points manche</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIN_MANCHE__POINTS_MANCHE = 1;

  /**
   * The number of structural features of the '<em>Fin Manche</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIN_MANCHE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.Points_mancheImpl <em>Points manche</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.Points_mancheImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getPoints_manche()
   * @generated
   */
  int POINTS_MANCHE = 12;

  /**
   * The feature id for the '<em><b>Vainqueur manche</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINTS_MANCHE__VAINQUEUR_MANCHE = 0;

  /**
   * The feature id for the '<em><b>Perdants manche</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINTS_MANCHE__PERDANTS_MANCHE = 1;

  /**
   * The number of structural features of the '<em>Points manche</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POINTS_MANCHE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.Perdants_mancheImpl <em>Perdants manche</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.Perdants_mancheImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getPerdants_manche()
   * @generated
   */
  int PERDANTS_MANCHE = 13;

  /**
   * The feature id for the '<em><b>Pm zero pts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERDANTS_MANCHE__PM_ZERO_PTS = 0;

  /**
   * The feature id for the '<em><b>Pm pts selon cartes restantes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERDANTS_MANCHE__PM_PTS_SELON_CARTES_RESTANTES = 1;

  /**
   * The number of structural features of the '<em>Perdants manche</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PERDANTS_MANCHE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.impl.Fin_PartieImpl <em>Fin Partie</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.impl.Fin_PartieImpl
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getFin_Partie()
   * @generated
   */
  int FIN_PARTIE = 14;

  /**
   * The feature id for the '<em><b>Vainqueur total</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIN_PARTIE__VAINQUEUR_TOTAL = 0;

  /**
   * The number of structural features of the '<em>Fin Partie</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FIN_PARTIE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.Etat_Main <em>Etat Main</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.Etat_Main
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getEtat_Main()
   * @generated
   */
  int ETAT_MAIN = 15;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.Nb_Mains <em>Nb Mains</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.Nb_Mains
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getNb_Mains()
   * @generated
   */
  int NB_MAINS = 16;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.Nb_Cartes_Mains <em>Nb Cartes Mains</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.Nb_Cartes_Mains
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getNb_Cartes_Mains()
   * @generated
   */
  int NB_CARTES_MAINS = 17;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.Nb_Talons <em>Nb Talons</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.Nb_Talons
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getNb_Talons()
   * @generated
   */
  int NB_TALONS = 18;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.Nb_cartes_jouables <em>Nb cartes jouables</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.Nb_cartes_jouables
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getNb_cartes_jouables()
   * @generated
   */
  int NB_CARTES_JOUABLES = 19;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.Interception <em>Interception</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.Interception
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getInterception()
   * @generated
   */
  int INTERCEPTION = 20;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.Nb_cartes_a_piocher <em>Nb cartes apiocher</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.Nb_cartes_a_piocher
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getNb_cartes_a_piocher()
   * @generated
   */
  int NB_CARTES_APIOCHER = 21;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.Jouer_apres_pioche <em>Jouer apres pioche</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.Jouer_apres_pioche
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getJouer_apres_pioche()
   * @generated
   */
  int JOUER_APRES_PIOCHE = 22;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.Vainqueur_manche <em>Vainqueur manche</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.Vainqueur_manche
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getVainqueur_manche()
   * @generated
   */
  int VAINQUEUR_MANCHE = 23;

  /**
   * The meta object id for the '{@link org.xtexthheinle.uno.myUno.Vainqueur_total <em>Vainqueur total</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtexthheinle.uno.myUno.Vainqueur_total
   * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getVainqueur_total()
   * @generated
   */
  int VAINQUEUR_TOTAL = 24;


  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Variante_UNO <em>Variante UNO</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variante UNO</em>'.
   * @see org.xtexthheinle.uno.myUno.Variante_UNO
   * @generated
   */
  EClass getVariante_UNO();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Variante_UNO#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtexthheinle.uno.myUno.Variante_UNO#getName()
   * @see #getVariante_UNO()
   * @generated
   */
  EAttribute getVariante_UNO_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Variante_UNO#getConfiguration_depart <em>Configuration depart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Configuration depart</em>'.
   * @see org.xtexthheinle.uno.myUno.Variante_UNO#getConfiguration_depart()
   * @see #getVariante_UNO()
   * @generated
   */
  EReference getVariante_UNO_Configuration_depart();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Variante_UNO#getManche <em>Manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Manche</em>'.
   * @see org.xtexthheinle.uno.myUno.Variante_UNO#getManche()
   * @see #getVariante_UNO()
   * @generated
   */
  EReference getVariante_UNO_Manche();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Variante_UNO#getFin_manche <em>Fin manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fin manche</em>'.
   * @see org.xtexthheinle.uno.myUno.Variante_UNO#getFin_manche()
   * @see #getVariante_UNO()
   * @generated
   */
  EReference getVariante_UNO_Fin_manche();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Variante_UNO#getFin_partie <em>Fin partie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fin partie</em>'.
   * @see org.xtexthheinle.uno.myUno.Variante_UNO#getFin_partie()
   * @see #getVariante_UNO()
   * @generated
   */
  EReference getVariante_UNO_Fin_partie();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Configuration_Depart <em>Configuration Depart</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Configuration Depart</em>'.
   * @see org.xtexthheinle.uno.myUno.Configuration_Depart
   * @generated
   */
  EClass getConfiguration_Depart();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Configuration_Depart#getMain <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Main</em>'.
   * @see org.xtexthheinle.uno.myUno.Configuration_Depart#getMain()
   * @see #getConfiguration_Depart()
   * @generated
   */
  EReference getConfiguration_Depart_Main();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Configuration_Depart#getTalon <em>Talon</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Talon</em>'.
   * @see org.xtexthheinle.uno.myUno.Configuration_Depart#getTalon()
   * @see #getConfiguration_Depart()
   * @generated
   */
  EReference getConfiguration_Depart_Talon();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Configuration_Depart#getRiviere <em>Riviere</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Riviere</em>'.
   * @see org.xtexthheinle.uno.myUno.Configuration_Depart#getRiviere()
   * @see #getConfiguration_Depart()
   * @generated
   */
  EAttribute getConfiguration_Depart_Riviere();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Configuration_Depart#getTemps_limite <em>Temps limite</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Temps limite</em>'.
   * @see org.xtexthheinle.uno.myUno.Configuration_Depart#getTemps_limite()
   * @see #getConfiguration_Depart()
   * @generated
   */
  EAttribute getConfiguration_Depart_Temps_limite();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Configuration_Depart#getSecondes <em>Secondes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Secondes</em>'.
   * @see org.xtexthheinle.uno.myUno.Configuration_Depart#getSecondes()
   * @see #getConfiguration_Depart()
   * @generated
   */
  EAttribute getConfiguration_Depart_Secondes();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Main <em>Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main</em>'.
   * @see org.xtexthheinle.uno.myUno.Main
   * @generated
   */
  EClass getMain();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Main#getEtat_main <em>Etat main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Etat main</em>'.
   * @see org.xtexthheinle.uno.myUno.Main#getEtat_main()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Etat_main();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Main#getNb_mains <em>Nb mains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nb mains</em>'.
   * @see org.xtexthheinle.uno.myUno.Main#getNb_mains()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Nb_mains();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Main#getNb_cartes_mains <em>Nb cartes mains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nb cartes mains</em>'.
   * @see org.xtexthheinle.uno.myUno.Main#getNb_cartes_mains()
   * @see #getMain()
   * @generated
   */
  EAttribute getMain_Nb_cartes_mains();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Talon <em>Talon</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Talon</em>'.
   * @see org.xtexthheinle.uno.myUno.Talon
   * @generated
   */
  EClass getTalon();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Talon#getNb_talons <em>Nb talons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nb talons</em>'.
   * @see org.xtexthheinle.uno.myUno.Talon#getNb_talons()
   * @see #getTalon()
   * @generated
   */
  EAttribute getTalon_Nb_talons();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Manche <em>Manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Manche</em>'.
   * @see org.xtexthheinle.uno.myUno.Manche
   * @generated
   */
  EClass getManche();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Manche#getInversion <em>Inversion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Inversion</em>'.
   * @see org.xtexthheinle.uno.myUno.Manche#getInversion()
   * @see #getManche()
   * @generated
   */
  EReference getManche_Inversion();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Manche#getTourner_les_mains <em>Tourner les mains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Tourner les mains</em>'.
   * @see org.xtexthheinle.uno.myUno.Manche#getTourner_les_mains()
   * @see #getManche()
   * @generated
   */
  EReference getManche_Tourner_les_mains();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Manche#getNb_cartes_jouables <em>Nb cartes jouables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nb cartes jouables</em>'.
   * @see org.xtexthheinle.uno.myUno.Manche#getNb_cartes_jouables()
   * @see #getManche()
   * @generated
   */
  EAttribute getManche_Nb_cartes_jouables();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Manche#getCartes_1_9 <em>Cartes 19</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cartes 19</em>'.
   * @see org.xtexthheinle.uno.myUno.Manche#getCartes_1_9()
   * @see #getManche()
   * @generated
   */
  EReference getManche_Cartes_1_9();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Manche#getPioche <em>Pioche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pioche</em>'.
   * @see org.xtexthheinle.uno.myUno.Manche#getPioche()
   * @see #getManche()
   * @generated
   */
  EReference getManche_Pioche();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Manche#getCumul <em>Cumul</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cumul</em>'.
   * @see org.xtexthheinle.uno.myUno.Manche#getCumul()
   * @see #getManche()
   * @generated
   */
  EReference getManche_Cumul();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Manche#getContestations <em>Contestations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Contestations</em>'.
   * @see org.xtexthheinle.uno.myUno.Manche#getContestations()
   * @see #getManche()
   * @generated
   */
  EReference getManche_Contestations();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Inversion <em>Inversion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Inversion</em>'.
   * @see org.xtexthheinle.uno.myUno.Inversion
   * @generated
   */
  EClass getInversion();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Inversion#getAvec_carte_inversion <em>Avec carte inversion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Avec carte inversion</em>'.
   * @see org.xtexthheinle.uno.myUno.Inversion#getAvec_carte_inversion()
   * @see #getInversion()
   * @generated
   */
  EAttribute getInversion_Avec_carte_inversion();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Inversion#getAvec_carte_sept <em>Avec carte sept</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Avec carte sept</em>'.
   * @see org.xtexthheinle.uno.myUno.Inversion#getAvec_carte_sept()
   * @see #getInversion()
   * @generated
   */
  EAttribute getInversion_Avec_carte_sept();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Tourner_les_mains <em>Tourner les mains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tourner les mains</em>'.
   * @see org.xtexthheinle.uno.myUno.Tourner_les_mains
   * @generated
   */
  EClass getTourner_les_mains();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Tourner_les_mains#getAvec_carte_zero <em>Avec carte zero</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Avec carte zero</em>'.
   * @see org.xtexthheinle.uno.myUno.Tourner_les_mains#getAvec_carte_zero()
   * @see #getTourner_les_mains()
   * @generated
   */
  EAttribute getTourner_les_mains_Avec_carte_zero();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Tourner_les_mains#getAvec_carte_uno <em>Avec carte uno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Avec carte uno</em>'.
   * @see org.xtexthheinle.uno.myUno.Tourner_les_mains#getAvec_carte_uno()
   * @see #getTourner_les_mains()
   * @generated
   */
  EAttribute getTourner_les_mains_Avec_carte_uno();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Cartes_1_9 <em>Cartes 19</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cartes 19</em>'.
   * @see org.xtexthheinle.uno.myUno.Cartes_1_9
   * @generated
   */
  EClass getCartes_1_9();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Cartes_1_9#getSuites <em>Suites</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Suites</em>'.
   * @see org.xtexthheinle.uno.myUno.Cartes_1_9#getSuites()
   * @see #getCartes_1_9()
   * @generated
   */
  EAttribute getCartes_1_9_Suites();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Cartes_1_9#getSuites_royales <em>Suites royales</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Suites royales</em>'.
   * @see org.xtexthheinle.uno.myUno.Cartes_1_9#getSuites_royales()
   * @see #getCartes_1_9()
   * @generated
   */
  EAttribute getCartes_1_9_Suites_royales();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Cartes_1_9#getInterception <em>Interception</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Interception</em>'.
   * @see org.xtexthheinle.uno.myUno.Cartes_1_9#getInterception()
   * @see #getCartes_1_9()
   * @generated
   */
  EAttribute getCartes_1_9_Interception();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Pioche <em>Pioche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pioche</em>'.
   * @see org.xtexthheinle.uno.myUno.Pioche
   * @generated
   */
  EClass getPioche();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Pioche#getNb_cartes_a_piocher <em>Nb cartes apiocher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Nb cartes apiocher</em>'.
   * @see org.xtexthheinle.uno.myUno.Pioche#getNb_cartes_a_piocher()
   * @see #getPioche()
   * @generated
   */
  EAttribute getPioche_Nb_cartes_a_piocher();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Pioche#getJouer_apres_pioche <em>Jouer apres pioche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Jouer apres pioche</em>'.
   * @see org.xtexthheinle.uno.myUno.Pioche#getJouer_apres_pioche()
   * @see #getPioche()
   * @generated
   */
  EAttribute getPioche_Jouer_apres_pioche();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Cumul <em>Cumul</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cumul</em>'.
   * @see org.xtexthheinle.uno.myUno.Cumul
   * @generated
   */
  EClass getCumul();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_plus_2 <em>Cumul plus 2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cumul plus 2</em>'.
   * @see org.xtexthheinle.uno.myUno.Cumul#getCumul_plus_2()
   * @see #getCumul()
   * @generated
   */
  EAttribute getCumul_Cumul_plus_2();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_plus_4 <em>Cumul plus 4</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cumul plus 4</em>'.
   * @see org.xtexthheinle.uno.myUno.Cumul#getCumul_plus_4()
   * @see #getCumul()
   * @generated
   */
  EAttribute getCumul_Cumul_plus_4();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_carte_couleur <em>Cumul carte couleur</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cumul carte couleur</em>'.
   * @see org.xtexthheinle.uno.myUno.Cumul#getCumul_carte_couleur()
   * @see #getCumul()
   * @generated
   */
  EAttribute getCumul_Cumul_carte_couleur();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Cumul#getCumul_carte_uno <em>Cumul carte uno</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cumul carte uno</em>'.
   * @see org.xtexthheinle.uno.myUno.Cumul#getCumul_carte_uno()
   * @see #getCumul()
   * @generated
   */
  EAttribute getCumul_Cumul_carte_uno();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Contestations <em>Contestations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Contestations</em>'.
   * @see org.xtexthheinle.uno.myUno.Contestations
   * @generated
   */
  EClass getContestations();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Contestations#getInter_contestable <em>Inter contestable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Inter contestable</em>'.
   * @see org.xtexthheinle.uno.myUno.Contestations#getInter_contestable()
   * @see #getContestations()
   * @generated
   */
  EAttribute getContestations_Inter_contestable();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Contestations#getPlus4_contestable <em>Plus4 contestable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Plus4 contestable</em>'.
   * @see org.xtexthheinle.uno.myUno.Contestations#getPlus4_contestable()
   * @see #getContestations()
   * @generated
   */
  EAttribute getContestations_Plus4_contestable();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Fin_Manche <em>Fin Manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fin Manche</em>'.
   * @see org.xtexthheinle.uno.myUno.Fin_Manche
   * @generated
   */
  EClass getFin_Manche();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Fin_Manche#getDire_uno_obligatoire <em>Dire uno obligatoire</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dire uno obligatoire</em>'.
   * @see org.xtexthheinle.uno.myUno.Fin_Manche#getDire_uno_obligatoire()
   * @see #getFin_Manche()
   * @generated
   */
  EAttribute getFin_Manche_Dire_uno_obligatoire();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Fin_Manche#getPoints_manche <em>Points manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Points manche</em>'.
   * @see org.xtexthheinle.uno.myUno.Fin_Manche#getPoints_manche()
   * @see #getFin_Manche()
   * @generated
   */
  EReference getFin_Manche_Points_manche();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Points_manche <em>Points manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Points manche</em>'.
   * @see org.xtexthheinle.uno.myUno.Points_manche
   * @generated
   */
  EClass getPoints_manche();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Points_manche#getVainqueur_manche <em>Vainqueur manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vainqueur manche</em>'.
   * @see org.xtexthheinle.uno.myUno.Points_manche#getVainqueur_manche()
   * @see #getPoints_manche()
   * @generated
   */
  EAttribute getPoints_manche_Vainqueur_manche();

  /**
   * Returns the meta object for the containment reference '{@link org.xtexthheinle.uno.myUno.Points_manche#getPerdants_manche <em>Perdants manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Perdants manche</em>'.
   * @see org.xtexthheinle.uno.myUno.Points_manche#getPerdants_manche()
   * @see #getPoints_manche()
   * @generated
   */
  EReference getPoints_manche_Perdants_manche();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Perdants_manche <em>Perdants manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Perdants manche</em>'.
   * @see org.xtexthheinle.uno.myUno.Perdants_manche
   * @generated
   */
  EClass getPerdants_manche();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Perdants_manche#getPm_zero_pts <em>Pm zero pts</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pm zero pts</em>'.
   * @see org.xtexthheinle.uno.myUno.Perdants_manche#getPm_zero_pts()
   * @see #getPerdants_manche()
   * @generated
   */
  EAttribute getPerdants_manche_Pm_zero_pts();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Perdants_manche#getPm_pts_selon_cartes_restantes <em>Pm pts selon cartes restantes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Pm pts selon cartes restantes</em>'.
   * @see org.xtexthheinle.uno.myUno.Perdants_manche#getPm_pts_selon_cartes_restantes()
   * @see #getPerdants_manche()
   * @generated
   */
  EAttribute getPerdants_manche_Pm_pts_selon_cartes_restantes();

  /**
   * Returns the meta object for class '{@link org.xtexthheinle.uno.myUno.Fin_Partie <em>Fin Partie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fin Partie</em>'.
   * @see org.xtexthheinle.uno.myUno.Fin_Partie
   * @generated
   */
  EClass getFin_Partie();

  /**
   * Returns the meta object for the attribute '{@link org.xtexthheinle.uno.myUno.Fin_Partie#getVainqueur_total <em>Vainqueur total</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Vainqueur total</em>'.
   * @see org.xtexthheinle.uno.myUno.Fin_Partie#getVainqueur_total()
   * @see #getFin_Partie()
   * @generated
   */
  EAttribute getFin_Partie_Vainqueur_total();

  /**
   * Returns the meta object for enum '{@link org.xtexthheinle.uno.myUno.Etat_Main <em>Etat Main</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Etat Main</em>'.
   * @see org.xtexthheinle.uno.myUno.Etat_Main
   * @generated
   */
  EEnum getEtat_Main();

  /**
   * Returns the meta object for enum '{@link org.xtexthheinle.uno.myUno.Nb_Mains <em>Nb Mains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Nb Mains</em>'.
   * @see org.xtexthheinle.uno.myUno.Nb_Mains
   * @generated
   */
  EEnum getNb_Mains();

  /**
   * Returns the meta object for enum '{@link org.xtexthheinle.uno.myUno.Nb_Cartes_Mains <em>Nb Cartes Mains</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Nb Cartes Mains</em>'.
   * @see org.xtexthheinle.uno.myUno.Nb_Cartes_Mains
   * @generated
   */
  EEnum getNb_Cartes_Mains();

  /**
   * Returns the meta object for enum '{@link org.xtexthheinle.uno.myUno.Nb_Talons <em>Nb Talons</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Nb Talons</em>'.
   * @see org.xtexthheinle.uno.myUno.Nb_Talons
   * @generated
   */
  EEnum getNb_Talons();

  /**
   * Returns the meta object for enum '{@link org.xtexthheinle.uno.myUno.Nb_cartes_jouables <em>Nb cartes jouables</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Nb cartes jouables</em>'.
   * @see org.xtexthheinle.uno.myUno.Nb_cartes_jouables
   * @generated
   */
  EEnum getNb_cartes_jouables();

  /**
   * Returns the meta object for enum '{@link org.xtexthheinle.uno.myUno.Interception <em>Interception</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Interception</em>'.
   * @see org.xtexthheinle.uno.myUno.Interception
   * @generated
   */
  EEnum getInterception();

  /**
   * Returns the meta object for enum '{@link org.xtexthheinle.uno.myUno.Nb_cartes_a_piocher <em>Nb cartes apiocher</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Nb cartes apiocher</em>'.
   * @see org.xtexthheinle.uno.myUno.Nb_cartes_a_piocher
   * @generated
   */
  EEnum getNb_cartes_a_piocher();

  /**
   * Returns the meta object for enum '{@link org.xtexthheinle.uno.myUno.Jouer_apres_pioche <em>Jouer apres pioche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Jouer apres pioche</em>'.
   * @see org.xtexthheinle.uno.myUno.Jouer_apres_pioche
   * @generated
   */
  EEnum getJouer_apres_pioche();

  /**
   * Returns the meta object for enum '{@link org.xtexthheinle.uno.myUno.Vainqueur_manche <em>Vainqueur manche</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Vainqueur manche</em>'.
   * @see org.xtexthheinle.uno.myUno.Vainqueur_manche
   * @generated
   */
  EEnum getVainqueur_manche();

  /**
   * Returns the meta object for enum '{@link org.xtexthheinle.uno.myUno.Vainqueur_total <em>Vainqueur total</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Vainqueur total</em>'.
   * @see org.xtexthheinle.uno.myUno.Vainqueur_total
   * @generated
   */
  EEnum getVainqueur_total();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyUnoFactory getMyUnoFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.Variante_UNOImpl <em>Variante UNO</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.Variante_UNOImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getVariante_UNO()
     * @generated
     */
    EClass VARIANTE_UNO = eINSTANCE.getVariante_UNO();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIANTE_UNO__NAME = eINSTANCE.getVariante_UNO_Name();

    /**
     * The meta object literal for the '<em><b>Configuration depart</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIANTE_UNO__CONFIGURATION_DEPART = eINSTANCE.getVariante_UNO_Configuration_depart();

    /**
     * The meta object literal for the '<em><b>Manche</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIANTE_UNO__MANCHE = eINSTANCE.getVariante_UNO_Manche();

    /**
     * The meta object literal for the '<em><b>Fin manche</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIANTE_UNO__FIN_MANCHE = eINSTANCE.getVariante_UNO_Fin_manche();

    /**
     * The meta object literal for the '<em><b>Fin partie</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VARIANTE_UNO__FIN_PARTIE = eINSTANCE.getVariante_UNO_Fin_partie();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.Configuration_DepartImpl <em>Configuration Depart</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.Configuration_DepartImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getConfiguration_Depart()
     * @generated
     */
    EClass CONFIGURATION_DEPART = eINSTANCE.getConfiguration_Depart();

    /**
     * The meta object literal for the '<em><b>Main</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATION_DEPART__MAIN = eINSTANCE.getConfiguration_Depart_Main();

    /**
     * The meta object literal for the '<em><b>Talon</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONFIGURATION_DEPART__TALON = eINSTANCE.getConfiguration_Depart_Talon();

    /**
     * The meta object literal for the '<em><b>Riviere</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION_DEPART__RIVIERE = eINSTANCE.getConfiguration_Depart_Riviere();

    /**
     * The meta object literal for the '<em><b>Temps limite</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION_DEPART__TEMPS_LIMITE = eINSTANCE.getConfiguration_Depart_Temps_limite();

    /**
     * The meta object literal for the '<em><b>Secondes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONFIGURATION_DEPART__SECONDES = eINSTANCE.getConfiguration_Depart_Secondes();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.MainImpl <em>Main</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.MainImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getMain()
     * @generated
     */
    EClass MAIN = eINSTANCE.getMain();

    /**
     * The meta object literal for the '<em><b>Etat main</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__ETAT_MAIN = eINSTANCE.getMain_Etat_main();

    /**
     * The meta object literal for the '<em><b>Nb mains</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__NB_MAINS = eINSTANCE.getMain_Nb_mains();

    /**
     * The meta object literal for the '<em><b>Nb cartes mains</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN__NB_CARTES_MAINS = eINSTANCE.getMain_Nb_cartes_mains();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.TalonImpl <em>Talon</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.TalonImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getTalon()
     * @generated
     */
    EClass TALON = eINSTANCE.getTalon();

    /**
     * The meta object literal for the '<em><b>Nb talons</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TALON__NB_TALONS = eINSTANCE.getTalon_Nb_talons();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.MancheImpl <em>Manche</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.MancheImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getManche()
     * @generated
     */
    EClass MANCHE = eINSTANCE.getManche();

    /**
     * The meta object literal for the '<em><b>Inversion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANCHE__INVERSION = eINSTANCE.getManche_Inversion();

    /**
     * The meta object literal for the '<em><b>Tourner les mains</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANCHE__TOURNER_LES_MAINS = eINSTANCE.getManche_Tourner_les_mains();

    /**
     * The meta object literal for the '<em><b>Nb cartes jouables</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MANCHE__NB_CARTES_JOUABLES = eINSTANCE.getManche_Nb_cartes_jouables();

    /**
     * The meta object literal for the '<em><b>Cartes 19</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANCHE__CARTES_19 = eINSTANCE.getManche_Cartes_1_9();

    /**
     * The meta object literal for the '<em><b>Pioche</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANCHE__PIOCHE = eINSTANCE.getManche_Pioche();

    /**
     * The meta object literal for the '<em><b>Cumul</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANCHE__CUMUL = eINSTANCE.getManche_Cumul();

    /**
     * The meta object literal for the '<em><b>Contestations</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MANCHE__CONTESTATIONS = eINSTANCE.getManche_Contestations();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.InversionImpl <em>Inversion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.InversionImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getInversion()
     * @generated
     */
    EClass INVERSION = eINSTANCE.getInversion();

    /**
     * The meta object literal for the '<em><b>Avec carte inversion</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INVERSION__AVEC_CARTE_INVERSION = eINSTANCE.getInversion_Avec_carte_inversion();

    /**
     * The meta object literal for the '<em><b>Avec carte sept</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INVERSION__AVEC_CARTE_SEPT = eINSTANCE.getInversion_Avec_carte_sept();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.Tourner_les_mainsImpl <em>Tourner les mains</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.Tourner_les_mainsImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getTourner_les_mains()
     * @generated
     */
    EClass TOURNER_LES_MAINS = eINSTANCE.getTourner_les_mains();

    /**
     * The meta object literal for the '<em><b>Avec carte zero</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOURNER_LES_MAINS__AVEC_CARTE_ZERO = eINSTANCE.getTourner_les_mains_Avec_carte_zero();

    /**
     * The meta object literal for the '<em><b>Avec carte uno</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOURNER_LES_MAINS__AVEC_CARTE_UNO = eINSTANCE.getTourner_les_mains_Avec_carte_uno();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.Cartes_1_9Impl <em>Cartes 19</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.Cartes_1_9Impl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getCartes_1_9()
     * @generated
     */
    EClass CARTES_19 = eINSTANCE.getCartes_1_9();

    /**
     * The meta object literal for the '<em><b>Suites</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARTES_19__SUITES = eINSTANCE.getCartes_1_9_Suites();

    /**
     * The meta object literal for the '<em><b>Suites royales</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARTES_19__SUITES_ROYALES = eINSTANCE.getCartes_1_9_Suites_royales();

    /**
     * The meta object literal for the '<em><b>Interception</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CARTES_19__INTERCEPTION = eINSTANCE.getCartes_1_9_Interception();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.PiocheImpl <em>Pioche</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.PiocheImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getPioche()
     * @generated
     */
    EClass PIOCHE = eINSTANCE.getPioche();

    /**
     * The meta object literal for the '<em><b>Nb cartes apiocher</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIOCHE__NB_CARTES_APIOCHER = eINSTANCE.getPioche_Nb_cartes_a_piocher();

    /**
     * The meta object literal for the '<em><b>Jouer apres pioche</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PIOCHE__JOUER_APRES_PIOCHE = eINSTANCE.getPioche_Jouer_apres_pioche();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.CumulImpl <em>Cumul</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.CumulImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getCumul()
     * @generated
     */
    EClass CUMUL = eINSTANCE.getCumul();

    /**
     * The meta object literal for the '<em><b>Cumul plus 2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUMUL__CUMUL_PLUS_2 = eINSTANCE.getCumul_Cumul_plus_2();

    /**
     * The meta object literal for the '<em><b>Cumul plus 4</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUMUL__CUMUL_PLUS_4 = eINSTANCE.getCumul_Cumul_plus_4();

    /**
     * The meta object literal for the '<em><b>Cumul carte couleur</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUMUL__CUMUL_CARTE_COULEUR = eINSTANCE.getCumul_Cumul_carte_couleur();

    /**
     * The meta object literal for the '<em><b>Cumul carte uno</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CUMUL__CUMUL_CARTE_UNO = eINSTANCE.getCumul_Cumul_carte_uno();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.ContestationsImpl <em>Contestations</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.ContestationsImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getContestations()
     * @generated
     */
    EClass CONTESTATIONS = eINSTANCE.getContestations();

    /**
     * The meta object literal for the '<em><b>Inter contestable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTESTATIONS__INTER_CONTESTABLE = eINSTANCE.getContestations_Inter_contestable();

    /**
     * The meta object literal for the '<em><b>Plus4 contestable</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTESTATIONS__PLUS4_CONTESTABLE = eINSTANCE.getContestations_Plus4_contestable();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.Fin_MancheImpl <em>Fin Manche</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.Fin_MancheImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getFin_Manche()
     * @generated
     */
    EClass FIN_MANCHE = eINSTANCE.getFin_Manche();

    /**
     * The meta object literal for the '<em><b>Dire uno obligatoire</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIN_MANCHE__DIRE_UNO_OBLIGATOIRE = eINSTANCE.getFin_Manche_Dire_uno_obligatoire();

    /**
     * The meta object literal for the '<em><b>Points manche</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FIN_MANCHE__POINTS_MANCHE = eINSTANCE.getFin_Manche_Points_manche();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.Points_mancheImpl <em>Points manche</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.Points_mancheImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getPoints_manche()
     * @generated
     */
    EClass POINTS_MANCHE = eINSTANCE.getPoints_manche();

    /**
     * The meta object literal for the '<em><b>Vainqueur manche</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute POINTS_MANCHE__VAINQUEUR_MANCHE = eINSTANCE.getPoints_manche_Vainqueur_manche();

    /**
     * The meta object literal for the '<em><b>Perdants manche</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference POINTS_MANCHE__PERDANTS_MANCHE = eINSTANCE.getPoints_manche_Perdants_manche();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.Perdants_mancheImpl <em>Perdants manche</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.Perdants_mancheImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getPerdants_manche()
     * @generated
     */
    EClass PERDANTS_MANCHE = eINSTANCE.getPerdants_manche();

    /**
     * The meta object literal for the '<em><b>Pm zero pts</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERDANTS_MANCHE__PM_ZERO_PTS = eINSTANCE.getPerdants_manche_Pm_zero_pts();

    /**
     * The meta object literal for the '<em><b>Pm pts selon cartes restantes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PERDANTS_MANCHE__PM_PTS_SELON_CARTES_RESTANTES = eINSTANCE.getPerdants_manche_Pm_pts_selon_cartes_restantes();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.impl.Fin_PartieImpl <em>Fin Partie</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.impl.Fin_PartieImpl
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getFin_Partie()
     * @generated
     */
    EClass FIN_PARTIE = eINSTANCE.getFin_Partie();

    /**
     * The meta object literal for the '<em><b>Vainqueur total</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FIN_PARTIE__VAINQUEUR_TOTAL = eINSTANCE.getFin_Partie_Vainqueur_total();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.Etat_Main <em>Etat Main</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.Etat_Main
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getEtat_Main()
     * @generated
     */
    EEnum ETAT_MAIN = eINSTANCE.getEtat_Main();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.Nb_Mains <em>Nb Mains</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.Nb_Mains
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getNb_Mains()
     * @generated
     */
    EEnum NB_MAINS = eINSTANCE.getNb_Mains();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.Nb_Cartes_Mains <em>Nb Cartes Mains</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.Nb_Cartes_Mains
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getNb_Cartes_Mains()
     * @generated
     */
    EEnum NB_CARTES_MAINS = eINSTANCE.getNb_Cartes_Mains();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.Nb_Talons <em>Nb Talons</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.Nb_Talons
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getNb_Talons()
     * @generated
     */
    EEnum NB_TALONS = eINSTANCE.getNb_Talons();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.Nb_cartes_jouables <em>Nb cartes jouables</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.Nb_cartes_jouables
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getNb_cartes_jouables()
     * @generated
     */
    EEnum NB_CARTES_JOUABLES = eINSTANCE.getNb_cartes_jouables();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.Interception <em>Interception</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.Interception
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getInterception()
     * @generated
     */
    EEnum INTERCEPTION = eINSTANCE.getInterception();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.Nb_cartes_a_piocher <em>Nb cartes apiocher</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.Nb_cartes_a_piocher
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getNb_cartes_a_piocher()
     * @generated
     */
    EEnum NB_CARTES_APIOCHER = eINSTANCE.getNb_cartes_a_piocher();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.Jouer_apres_pioche <em>Jouer apres pioche</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.Jouer_apres_pioche
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getJouer_apres_pioche()
     * @generated
     */
    EEnum JOUER_APRES_PIOCHE = eINSTANCE.getJouer_apres_pioche();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.Vainqueur_manche <em>Vainqueur manche</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.Vainqueur_manche
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getVainqueur_manche()
     * @generated
     */
    EEnum VAINQUEUR_MANCHE = eINSTANCE.getVainqueur_manche();

    /**
     * The meta object literal for the '{@link org.xtexthheinle.uno.myUno.Vainqueur_total <em>Vainqueur total</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtexthheinle.uno.myUno.Vainqueur_total
     * @see org.xtexthheinle.uno.myUno.impl.MyUnoPackageImpl#getVainqueur_total()
     * @generated
     */
    EEnum VAINQUEUR_TOTAL = eINSTANCE.getVainqueur_total();

  }

} //MyUnoPackage
