/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage
 * @generated
 */
public interface MyUnoFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyUnoFactory eINSTANCE = org.xtexthheinle.uno.myUno.impl.MyUnoFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Variante UNO</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Variante UNO</em>'.
   * @generated
   */
  Variante_UNO createVariante_UNO();

  /**
   * Returns a new object of class '<em>Configuration Depart</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Configuration Depart</em>'.
   * @generated
   */
  Configuration_Depart createConfiguration_Depart();

  /**
   * Returns a new object of class '<em>Main</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Main</em>'.
   * @generated
   */
  Main createMain();

  /**
   * Returns a new object of class '<em>Talon</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Talon</em>'.
   * @generated
   */
  Talon createTalon();

  /**
   * Returns a new object of class '<em>Manche</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Manche</em>'.
   * @generated
   */
  Manche createManche();

  /**
   * Returns a new object of class '<em>Inversion</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inversion</em>'.
   * @generated
   */
  Inversion createInversion();

  /**
   * Returns a new object of class '<em>Tourner les mains</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Tourner les mains</em>'.
   * @generated
   */
  Tourner_les_mains createTourner_les_mains();

  /**
   * Returns a new object of class '<em>Cartes 19</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cartes 19</em>'.
   * @generated
   */
  Cartes_1_9 createCartes_1_9();

  /**
   * Returns a new object of class '<em>Pioche</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Pioche</em>'.
   * @generated
   */
  Pioche createPioche();

  /**
   * Returns a new object of class '<em>Cumul</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Cumul</em>'.
   * @generated
   */
  Cumul createCumul();

  /**
   * Returns a new object of class '<em>Contestations</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Contestations</em>'.
   * @generated
   */
  Contestations createContestations();

  /**
   * Returns a new object of class '<em>Fin Manche</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fin Manche</em>'.
   * @generated
   */
  Fin_Manche createFin_Manche();

  /**
   * Returns a new object of class '<em>Points manche</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Points manche</em>'.
   * @generated
   */
  Points_manche createPoints_manche();

  /**
   * Returns a new object of class '<em>Perdants manche</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Perdants manche</em>'.
   * @generated
   */
  Perdants_manche createPerdants_manche();

  /**
   * Returns a new object of class '<em>Fin Partie</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fin Partie</em>'.
   * @generated
   */
  Fin_Partie createFin_Partie();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyUnoPackage getMyUnoPackage();

} //MyUnoFactory
