/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Nb cartes jouables</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getNb_cartes_jouables()
 * @model
 * @generated
 */
public enum Nb_cartes_jouables implements Enumerator
{
  /**
   * The '<em><b>Une par une</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNE_PAR_UNE_VALUE
   * @generated
   * @ordered
   */
  UNE_PAR_UNE(0, "une_par_une", "une_par_une"),

  /**
   * The '<em><b>Plusieurs ala fois autorise</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PLUSIEURS_ALA_FOIS_AUTORISE_VALUE
   * @generated
   * @ordered
   */
  PLUSIEURS_ALA_FOIS_AUTORISE(1, "plusieurs_a_la_fois_autorise", "plusieurs_a_la_fois_autorise");

  /**
   * The '<em><b>Une par une</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNE_PAR_UNE
   * @model name="une_par_une"
   * @generated
   * @ordered
   */
  public static final int UNE_PAR_UNE_VALUE = 0;

  /**
   * The '<em><b>Plusieurs ala fois autorise</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PLUSIEURS_ALA_FOIS_AUTORISE
   * @model name="plusieurs_a_la_fois_autorise"
   * @generated
   * @ordered
   */
  public static final int PLUSIEURS_ALA_FOIS_AUTORISE_VALUE = 1;

  /**
   * An array of all the '<em><b>Nb cartes jouables</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Nb_cartes_jouables[] VALUES_ARRAY =
    new Nb_cartes_jouables[]
    {
      UNE_PAR_UNE,
      PLUSIEURS_ALA_FOIS_AUTORISE,
    };

  /**
   * A public read-only list of all the '<em><b>Nb cartes jouables</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Nb_cartes_jouables> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Nb cartes jouables</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nb_cartes_jouables get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Nb_cartes_jouables result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Nb cartes jouables</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nb_cartes_jouables getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Nb_cartes_jouables result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Nb cartes jouables</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nb_cartes_jouables get(int value)
  {
    switch (value)
    {
      case UNE_PAR_UNE_VALUE: return UNE_PAR_UNE;
      case PLUSIEURS_ALA_FOIS_AUTORISE_VALUE: return PLUSIEURS_ALA_FOIS_AUTORISE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Nb_cartes_jouables(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Nb_cartes_jouables
