/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Nb cartes apiocher</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getNb_cartes_a_piocher()
 * @model
 * @generated
 */
public enum Nb_cartes_a_piocher implements Enumerator
{
  /**
   * The '<em><b>Une seule</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNE_SEULE_VALUE
   * @generated
   * @ordered
   */
  UNE_SEULE(0, "une_seule", "une_seule"),

  /**
   * The '<em><b>Au plus trois</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AU_PLUS_TROIS_VALUE
   * @generated
   * @ordered
   */
  AU_PLUS_TROIS(1, "au_plus_trois", "au_plus_trois");

  /**
   * The '<em><b>Une seule</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #UNE_SEULE
   * @model name="une_seule"
   * @generated
   * @ordered
   */
  public static final int UNE_SEULE_VALUE = 0;

  /**
   * The '<em><b>Au plus trois</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #AU_PLUS_TROIS
   * @model name="au_plus_trois"
   * @generated
   * @ordered
   */
  public static final int AU_PLUS_TROIS_VALUE = 1;

  /**
   * An array of all the '<em><b>Nb cartes apiocher</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Nb_cartes_a_piocher[] VALUES_ARRAY =
    new Nb_cartes_a_piocher[]
    {
      UNE_SEULE,
      AU_PLUS_TROIS,
    };

  /**
   * A public read-only list of all the '<em><b>Nb cartes apiocher</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Nb_cartes_a_piocher> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Nb cartes apiocher</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nb_cartes_a_piocher get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Nb_cartes_a_piocher result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Nb cartes apiocher</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nb_cartes_a_piocher getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Nb_cartes_a_piocher result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Nb cartes apiocher</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nb_cartes_a_piocher get(int value)
  {
    switch (value)
    {
      case UNE_SEULE_VALUE: return UNE_SEULE;
      case AU_PLUS_TROIS_VALUE: return AU_PLUS_TROIS;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Nb_cartes_a_piocher(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Nb_cartes_a_piocher
