/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Nb Cartes Mains</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getNb_Cartes_Mains()
 * @model
 * @generated
 */
public enum Nb_Cartes_Mains implements Enumerator
{
  /**
   * The '<em><b>Sept cartes</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SEPT_CARTES_VALUE
   * @generated
   * @ordered
   */
  SEPT_CARTES(0, "sept_cartes", "7"),

  /**
   * The '<em><b>Quatre cartes</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #QUATRE_CARTES_VALUE
   * @generated
   * @ordered
   */
  QUATRE_CARTES(1, "quatre_cartes", "4"),

  /**
   * The '<em><b>Cinq cartes</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CINQ_CARTES_VALUE
   * @generated
   * @ordered
   */
  CINQ_CARTES(2, "cinq_cartes", "5");

  /**
   * The '<em><b>Sept cartes</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SEPT_CARTES
   * @model name="sept_cartes" literal="7"
   * @generated
   * @ordered
   */
  public static final int SEPT_CARTES_VALUE = 0;

  /**
   * The '<em><b>Quatre cartes</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #QUATRE_CARTES
   * @model name="quatre_cartes" literal="4"
   * @generated
   * @ordered
   */
  public static final int QUATRE_CARTES_VALUE = 1;

  /**
   * The '<em><b>Cinq cartes</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CINQ_CARTES
   * @model name="cinq_cartes" literal="5"
   * @generated
   * @ordered
   */
  public static final int CINQ_CARTES_VALUE = 2;

  /**
   * An array of all the '<em><b>Nb Cartes Mains</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Nb_Cartes_Mains[] VALUES_ARRAY =
    new Nb_Cartes_Mains[]
    {
      SEPT_CARTES,
      QUATRE_CARTES,
      CINQ_CARTES,
    };

  /**
   * A public read-only list of all the '<em><b>Nb Cartes Mains</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Nb_Cartes_Mains> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Nb Cartes Mains</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nb_Cartes_Mains get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Nb_Cartes_Mains result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Nb Cartes Mains</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nb_Cartes_Mains getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Nb_Cartes_Mains result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Nb Cartes Mains</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Nb_Cartes_Mains get(int value)
  {
    switch (value)
    {
      case SEPT_CARTES_VALUE: return SEPT_CARTES;
      case QUATRE_CARTES_VALUE: return QUATRE_CARTES;
      case CINQ_CARTES_VALUE: return CINQ_CARTES;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Nb_Cartes_Mains(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Nb_Cartes_Mains
