/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Perdants manche</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.Perdants_manche#getPm_zero_pts <em>Pm zero pts</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Perdants_manche#getPm_pts_selon_cartes_restantes <em>Pm pts selon cartes restantes</em>}</li>
 * </ul>
 *
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getPerdants_manche()
 * @model
 * @generated
 */
public interface Perdants_manche extends EObject
{
  /**
   * Returns the value of the '<em><b>Pm zero pts</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pm zero pts</em>' attribute.
   * @see #setPm_zero_pts(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getPerdants_manche_Pm_zero_pts()
   * @model
   * @generated
   */
  String getPm_zero_pts();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Perdants_manche#getPm_zero_pts <em>Pm zero pts</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pm zero pts</em>' attribute.
   * @see #getPm_zero_pts()
   * @generated
   */
  void setPm_zero_pts(String value);

  /**
   * Returns the value of the '<em><b>Pm pts selon cartes restantes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pm pts selon cartes restantes</em>' attribute.
   * @see #setPm_pts_selon_cartes_restantes(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getPerdants_manche_Pm_pts_selon_cartes_restantes()
   * @model
   * @generated
   */
  String getPm_pts_selon_cartes_restantes();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Perdants_manche#getPm_pts_selon_cartes_restantes <em>Pm pts selon cartes restantes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pm pts selon cartes restantes</em>' attribute.
   * @see #getPm_pts_selon_cartes_restantes()
   * @generated
   */
  void setPm_pts_selon_cartes_restantes(String value);

} // Perdants_manche
