/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Variante UNO</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.Variante_UNO#getName <em>Name</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Variante_UNO#getConfiguration_depart <em>Configuration depart</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Variante_UNO#getManche <em>Manche</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Variante_UNO#getFin_manche <em>Fin manche</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.Variante_UNO#getFin_partie <em>Fin partie</em>}</li>
 * </ul>
 *
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getVariante_UNO()
 * @model
 * @generated
 */
public interface Variante_UNO extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getVariante_UNO_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Variante_UNO#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Configuration depart</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Configuration depart</em>' containment reference.
   * @see #setConfiguration_depart(Configuration_Depart)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getVariante_UNO_Configuration_depart()
   * @model containment="true"
   * @generated
   */
  Configuration_Depart getConfiguration_depart();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Variante_UNO#getConfiguration_depart <em>Configuration depart</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Configuration depart</em>' containment reference.
   * @see #getConfiguration_depart()
   * @generated
   */
  void setConfiguration_depart(Configuration_Depart value);

  /**
   * Returns the value of the '<em><b>Manche</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Manche</em>' containment reference.
   * @see #setManche(Manche)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getVariante_UNO_Manche()
   * @model containment="true"
   * @generated
   */
  Manche getManche();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Variante_UNO#getManche <em>Manche</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Manche</em>' containment reference.
   * @see #getManche()
   * @generated
   */
  void setManche(Manche value);

  /**
   * Returns the value of the '<em><b>Fin manche</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fin manche</em>' containment reference.
   * @see #setFin_manche(Fin_Manche)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getVariante_UNO_Fin_manche()
   * @model containment="true"
   * @generated
   */
  Fin_Manche getFin_manche();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Variante_UNO#getFin_manche <em>Fin manche</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fin manche</em>' containment reference.
   * @see #getFin_manche()
   * @generated
   */
  void setFin_manche(Fin_Manche value);

  /**
   * Returns the value of the '<em><b>Fin partie</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fin partie</em>' containment reference.
   * @see #setFin_partie(Fin_Partie)
   * @see org.xtexthheinle.uno.myUno.MyUnoPackage#getVariante_UNO_Fin_partie()
   * @model containment="true"
   * @generated
   */
  Fin_Partie getFin_partie();

  /**
   * Sets the value of the '{@link org.xtexthheinle.uno.myUno.Variante_UNO#getFin_partie <em>Fin partie</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fin partie</em>' containment reference.
   * @see #getFin_partie()
   * @generated
   */
  void setFin_partie(Fin_Partie value);

} // Variante_UNO
