/*
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MyUnoUiModule extends AbstractMyUnoUiModule {

	public MyUnoUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
