/*
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyUnoRuntimeModule extends AbstractMyUnoRuntimeModule {
}
