/*
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MyUnoStandaloneSetup extends MyUnoStandaloneSetupGenerated {

	public static void doSetup() {
		new MyUnoStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
