/*
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtexthheinle.uno.ui.internal.UnoActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyUnoExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(UnoActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		UnoActivator activator = UnoActivator.getInstance();
		return activator != null ? activator.getInjector(UnoActivator.ORG_XTEXTHHEINLE_UNO_MYUNO) : null;
	}

}
