/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtexthheinle.uno.myUno.Configuration_Depart;
import org.xtexthheinle.uno.myUno.Main;
import org.xtexthheinle.uno.myUno.MyUnoPackage;
import org.xtexthheinle.uno.myUno.Talon;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Configuration Depart</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Configuration_DepartImpl#getMain <em>Main</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Configuration_DepartImpl#getTalon <em>Talon</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Configuration_DepartImpl#getRiviere <em>Riviere</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Configuration_DepartImpl#getTemps_limite <em>Temps limite</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Configuration_DepartImpl#getSecondes <em>Secondes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Configuration_DepartImpl extends MinimalEObjectImpl.Container implements Configuration_Depart
{
  /**
   * The cached value of the '{@link #getMain() <em>Main</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMain()
   * @generated
   * @ordered
   */
  protected Main main;

  /**
   * The cached value of the '{@link #getTalon() <em>Talon</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTalon()
   * @generated
   * @ordered
   */
  protected Talon talon;

  /**
   * The default value of the '{@link #getRiviere() <em>Riviere</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRiviere()
   * @generated
   * @ordered
   */
  protected static final String RIVIERE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRiviere() <em>Riviere</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRiviere()
   * @generated
   * @ordered
   */
  protected String riviere = RIVIERE_EDEFAULT;

  /**
   * The default value of the '{@link #getTemps_limite() <em>Temps limite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTemps_limite()
   * @generated
   * @ordered
   */
  protected static final String TEMPS_LIMITE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTemps_limite() <em>Temps limite</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTemps_limite()
   * @generated
   * @ordered
   */
  protected String temps_limite = TEMPS_LIMITE_EDEFAULT;

  /**
   * The default value of the '{@link #getSecondes() <em>Secondes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecondes()
   * @generated
   * @ordered
   */
  protected static final int SECONDES_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSecondes() <em>Secondes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSecondes()
   * @generated
   * @ordered
   */
  protected int secondes = SECONDES_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Configuration_DepartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoPackage.Literals.CONFIGURATION_DEPART;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Main getMain()
  {
    return main;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMain(Main newMain, NotificationChain msgs)
  {
    Main oldMain = main;
    main = newMain;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyUnoPackage.CONFIGURATION_DEPART__MAIN, oldMain, newMain);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMain(Main newMain)
  {
    if (newMain != main)
    {
      NotificationChain msgs = null;
      if (main != null)
        msgs = ((InternalEObject)main).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyUnoPackage.CONFIGURATION_DEPART__MAIN, null, msgs);
      if (newMain != null)
        msgs = ((InternalEObject)newMain).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyUnoPackage.CONFIGURATION_DEPART__MAIN, null, msgs);
      msgs = basicSetMain(newMain, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.CONFIGURATION_DEPART__MAIN, newMain, newMain));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Talon getTalon()
  {
    return talon;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTalon(Talon newTalon, NotificationChain msgs)
  {
    Talon oldTalon = talon;
    talon = newTalon;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyUnoPackage.CONFIGURATION_DEPART__TALON, oldTalon, newTalon);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTalon(Talon newTalon)
  {
    if (newTalon != talon)
    {
      NotificationChain msgs = null;
      if (talon != null)
        msgs = ((InternalEObject)talon).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyUnoPackage.CONFIGURATION_DEPART__TALON, null, msgs);
      if (newTalon != null)
        msgs = ((InternalEObject)newTalon).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyUnoPackage.CONFIGURATION_DEPART__TALON, null, msgs);
      msgs = basicSetTalon(newTalon, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.CONFIGURATION_DEPART__TALON, newTalon, newTalon));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRiviere()
  {
    return riviere;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRiviere(String newRiviere)
  {
    String oldRiviere = riviere;
    riviere = newRiviere;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.CONFIGURATION_DEPART__RIVIERE, oldRiviere, riviere));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTemps_limite()
  {
    return temps_limite;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTemps_limite(String newTemps_limite)
  {
    String oldTemps_limite = temps_limite;
    temps_limite = newTemps_limite;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.CONFIGURATION_DEPART__TEMPS_LIMITE, oldTemps_limite, temps_limite));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSecondes()
  {
    return secondes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSecondes(int newSecondes)
  {
    int oldSecondes = secondes;
    secondes = newSecondes;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.CONFIGURATION_DEPART__SECONDES, oldSecondes, secondes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyUnoPackage.CONFIGURATION_DEPART__MAIN:
        return basicSetMain(null, msgs);
      case MyUnoPackage.CONFIGURATION_DEPART__TALON:
        return basicSetTalon(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoPackage.CONFIGURATION_DEPART__MAIN:
        return getMain();
      case MyUnoPackage.CONFIGURATION_DEPART__TALON:
        return getTalon();
      case MyUnoPackage.CONFIGURATION_DEPART__RIVIERE:
        return getRiviere();
      case MyUnoPackage.CONFIGURATION_DEPART__TEMPS_LIMITE:
        return getTemps_limite();
      case MyUnoPackage.CONFIGURATION_DEPART__SECONDES:
        return getSecondes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoPackage.CONFIGURATION_DEPART__MAIN:
        setMain((Main)newValue);
        return;
      case MyUnoPackage.CONFIGURATION_DEPART__TALON:
        setTalon((Talon)newValue);
        return;
      case MyUnoPackage.CONFIGURATION_DEPART__RIVIERE:
        setRiviere((String)newValue);
        return;
      case MyUnoPackage.CONFIGURATION_DEPART__TEMPS_LIMITE:
        setTemps_limite((String)newValue);
        return;
      case MyUnoPackage.CONFIGURATION_DEPART__SECONDES:
        setSecondes((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.CONFIGURATION_DEPART__MAIN:
        setMain((Main)null);
        return;
      case MyUnoPackage.CONFIGURATION_DEPART__TALON:
        setTalon((Talon)null);
        return;
      case MyUnoPackage.CONFIGURATION_DEPART__RIVIERE:
        setRiviere(RIVIERE_EDEFAULT);
        return;
      case MyUnoPackage.CONFIGURATION_DEPART__TEMPS_LIMITE:
        setTemps_limite(TEMPS_LIMITE_EDEFAULT);
        return;
      case MyUnoPackage.CONFIGURATION_DEPART__SECONDES:
        setSecondes(SECONDES_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.CONFIGURATION_DEPART__MAIN:
        return main != null;
      case MyUnoPackage.CONFIGURATION_DEPART__TALON:
        return talon != null;
      case MyUnoPackage.CONFIGURATION_DEPART__RIVIERE:
        return RIVIERE_EDEFAULT == null ? riviere != null : !RIVIERE_EDEFAULT.equals(riviere);
      case MyUnoPackage.CONFIGURATION_DEPART__TEMPS_LIMITE:
        return TEMPS_LIMITE_EDEFAULT == null ? temps_limite != null : !TEMPS_LIMITE_EDEFAULT.equals(temps_limite);
      case MyUnoPackage.CONFIGURATION_DEPART__SECONDES:
        return secondes != SECONDES_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (riviere: ");
    result.append(riviere);
    result.append(", temps_limite: ");
    result.append(temps_limite);
    result.append(", secondes: ");
    result.append(secondes);
    result.append(')');
    return result.toString();
  }

} //Configuration_DepartImpl
