/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtexthheinle.uno.myUno.Cumul;
import org.xtexthheinle.uno.myUno.MyUnoPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cumul</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.CumulImpl#getCumul_plus_2 <em>Cumul plus 2</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.CumulImpl#getCumul_plus_4 <em>Cumul plus 4</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.CumulImpl#getCumul_carte_couleur <em>Cumul carte couleur</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.CumulImpl#getCumul_carte_uno <em>Cumul carte uno</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CumulImpl extends MinimalEObjectImpl.Container implements Cumul
{
  /**
   * The default value of the '{@link #getCumul_plus_2() <em>Cumul plus 2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumul_plus_2()
   * @generated
   * @ordered
   */
  protected static final String CUMUL_PLUS_2_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCumul_plus_2() <em>Cumul plus 2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumul_plus_2()
   * @generated
   * @ordered
   */
  protected String cumul_plus_2 = CUMUL_PLUS_2_EDEFAULT;

  /**
   * The default value of the '{@link #getCumul_plus_4() <em>Cumul plus 4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumul_plus_4()
   * @generated
   * @ordered
   */
  protected static final String CUMUL_PLUS_4_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCumul_plus_4() <em>Cumul plus 4</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumul_plus_4()
   * @generated
   * @ordered
   */
  protected String cumul_plus_4 = CUMUL_PLUS_4_EDEFAULT;

  /**
   * The default value of the '{@link #getCumul_carte_couleur() <em>Cumul carte couleur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumul_carte_couleur()
   * @generated
   * @ordered
   */
  protected static final String CUMUL_CARTE_COULEUR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCumul_carte_couleur() <em>Cumul carte couleur</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumul_carte_couleur()
   * @generated
   * @ordered
   */
  protected String cumul_carte_couleur = CUMUL_CARTE_COULEUR_EDEFAULT;

  /**
   * The default value of the '{@link #getCumul_carte_uno() <em>Cumul carte uno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumul_carte_uno()
   * @generated
   * @ordered
   */
  protected static final String CUMUL_CARTE_UNO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getCumul_carte_uno() <em>Cumul carte uno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCumul_carte_uno()
   * @generated
   * @ordered
   */
  protected String cumul_carte_uno = CUMUL_CARTE_UNO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CumulImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoPackage.Literals.CUMUL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCumul_plus_2()
  {
    return cumul_plus_2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCumul_plus_2(String newCumul_plus_2)
  {
    String oldCumul_plus_2 = cumul_plus_2;
    cumul_plus_2 = newCumul_plus_2;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.CUMUL__CUMUL_PLUS_2, oldCumul_plus_2, cumul_plus_2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCumul_plus_4()
  {
    return cumul_plus_4;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCumul_plus_4(String newCumul_plus_4)
  {
    String oldCumul_plus_4 = cumul_plus_4;
    cumul_plus_4 = newCumul_plus_4;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.CUMUL__CUMUL_PLUS_4, oldCumul_plus_4, cumul_plus_4));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCumul_carte_couleur()
  {
    return cumul_carte_couleur;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCumul_carte_couleur(String newCumul_carte_couleur)
  {
    String oldCumul_carte_couleur = cumul_carte_couleur;
    cumul_carte_couleur = newCumul_carte_couleur;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.CUMUL__CUMUL_CARTE_COULEUR, oldCumul_carte_couleur, cumul_carte_couleur));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getCumul_carte_uno()
  {
    return cumul_carte_uno;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCumul_carte_uno(String newCumul_carte_uno)
  {
    String oldCumul_carte_uno = cumul_carte_uno;
    cumul_carte_uno = newCumul_carte_uno;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.CUMUL__CUMUL_CARTE_UNO, oldCumul_carte_uno, cumul_carte_uno));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoPackage.CUMUL__CUMUL_PLUS_2:
        return getCumul_plus_2();
      case MyUnoPackage.CUMUL__CUMUL_PLUS_4:
        return getCumul_plus_4();
      case MyUnoPackage.CUMUL__CUMUL_CARTE_COULEUR:
        return getCumul_carte_couleur();
      case MyUnoPackage.CUMUL__CUMUL_CARTE_UNO:
        return getCumul_carte_uno();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoPackage.CUMUL__CUMUL_PLUS_2:
        setCumul_plus_2((String)newValue);
        return;
      case MyUnoPackage.CUMUL__CUMUL_PLUS_4:
        setCumul_plus_4((String)newValue);
        return;
      case MyUnoPackage.CUMUL__CUMUL_CARTE_COULEUR:
        setCumul_carte_couleur((String)newValue);
        return;
      case MyUnoPackage.CUMUL__CUMUL_CARTE_UNO:
        setCumul_carte_uno((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.CUMUL__CUMUL_PLUS_2:
        setCumul_plus_2(CUMUL_PLUS_2_EDEFAULT);
        return;
      case MyUnoPackage.CUMUL__CUMUL_PLUS_4:
        setCumul_plus_4(CUMUL_PLUS_4_EDEFAULT);
        return;
      case MyUnoPackage.CUMUL__CUMUL_CARTE_COULEUR:
        setCumul_carte_couleur(CUMUL_CARTE_COULEUR_EDEFAULT);
        return;
      case MyUnoPackage.CUMUL__CUMUL_CARTE_UNO:
        setCumul_carte_uno(CUMUL_CARTE_UNO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.CUMUL__CUMUL_PLUS_2:
        return CUMUL_PLUS_2_EDEFAULT == null ? cumul_plus_2 != null : !CUMUL_PLUS_2_EDEFAULT.equals(cumul_plus_2);
      case MyUnoPackage.CUMUL__CUMUL_PLUS_4:
        return CUMUL_PLUS_4_EDEFAULT == null ? cumul_plus_4 != null : !CUMUL_PLUS_4_EDEFAULT.equals(cumul_plus_4);
      case MyUnoPackage.CUMUL__CUMUL_CARTE_COULEUR:
        return CUMUL_CARTE_COULEUR_EDEFAULT == null ? cumul_carte_couleur != null : !CUMUL_CARTE_COULEUR_EDEFAULT.equals(cumul_carte_couleur);
      case MyUnoPackage.CUMUL__CUMUL_CARTE_UNO:
        return CUMUL_CARTE_UNO_EDEFAULT == null ? cumul_carte_uno != null : !CUMUL_CARTE_UNO_EDEFAULT.equals(cumul_carte_uno);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (cumul_plus_2: ");
    result.append(cumul_plus_2);
    result.append(", cumul_plus_4: ");
    result.append(cumul_plus_4);
    result.append(", cumul_carte_couleur: ");
    result.append(cumul_carte_couleur);
    result.append(", cumul_carte_uno: ");
    result.append(cumul_carte_uno);
    result.append(')');
    return result.toString();
  }

} //CumulImpl
