/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtexthheinle.uno.myUno.Fin_Partie;
import org.xtexthheinle.uno.myUno.MyUnoPackage;
import org.xtexthheinle.uno.myUno.Vainqueur_total;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fin Partie</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Fin_PartieImpl#getVainqueur_total <em>Vainqueur total</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Fin_PartieImpl extends MinimalEObjectImpl.Container implements Fin_Partie
{
  /**
   * The default value of the '{@link #getVainqueur_total() <em>Vainqueur total</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVainqueur_total()
   * @generated
   * @ordered
   */
  protected static final Vainqueur_total VAINQUEUR_TOTAL_EDEFAULT = Vainqueur_total.SCORE_LE_PLUS_GRD;

  /**
   * The cached value of the '{@link #getVainqueur_total() <em>Vainqueur total</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVainqueur_total()
   * @generated
   * @ordered
   */
  protected Vainqueur_total vainqueur_total = VAINQUEUR_TOTAL_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Fin_PartieImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoPackage.Literals.FIN_PARTIE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Vainqueur_total getVainqueur_total()
  {
    return vainqueur_total;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVainqueur_total(Vainqueur_total newVainqueur_total)
  {
    Vainqueur_total oldVainqueur_total = vainqueur_total;
    vainqueur_total = newVainqueur_total == null ? VAINQUEUR_TOTAL_EDEFAULT : newVainqueur_total;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.FIN_PARTIE__VAINQUEUR_TOTAL, oldVainqueur_total, vainqueur_total));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoPackage.FIN_PARTIE__VAINQUEUR_TOTAL:
        return getVainqueur_total();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoPackage.FIN_PARTIE__VAINQUEUR_TOTAL:
        setVainqueur_total((Vainqueur_total)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.FIN_PARTIE__VAINQUEUR_TOTAL:
        setVainqueur_total(VAINQUEUR_TOTAL_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.FIN_PARTIE__VAINQUEUR_TOTAL:
        return vainqueur_total != VAINQUEUR_TOTAL_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (vainqueur_total: ");
    result.append(vainqueur_total);
    result.append(')');
    return result.toString();
  }

} //Fin_PartieImpl
