/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtexthheinle.uno.myUno.MyUnoPackage;
import org.xtexthheinle.uno.myUno.Perdants_manche;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Perdants manche</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Perdants_mancheImpl#getPm_zero_pts <em>Pm zero pts</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Perdants_mancheImpl#getPm_pts_selon_cartes_restantes <em>Pm pts selon cartes restantes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Perdants_mancheImpl extends MinimalEObjectImpl.Container implements Perdants_manche
{
  /**
   * The default value of the '{@link #getPm_zero_pts() <em>Pm zero pts</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPm_zero_pts()
   * @generated
   * @ordered
   */
  protected static final String PM_ZERO_PTS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPm_zero_pts() <em>Pm zero pts</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPm_zero_pts()
   * @generated
   * @ordered
   */
  protected String pm_zero_pts = PM_ZERO_PTS_EDEFAULT;

  /**
   * The default value of the '{@link #getPm_pts_selon_cartes_restantes() <em>Pm pts selon cartes restantes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPm_pts_selon_cartes_restantes()
   * @generated
   * @ordered
   */
  protected static final String PM_PTS_SELON_CARTES_RESTANTES_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPm_pts_selon_cartes_restantes() <em>Pm pts selon cartes restantes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPm_pts_selon_cartes_restantes()
   * @generated
   * @ordered
   */
  protected String pm_pts_selon_cartes_restantes = PM_PTS_SELON_CARTES_RESTANTES_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Perdants_mancheImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoPackage.Literals.PERDANTS_MANCHE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPm_zero_pts()
  {
    return pm_zero_pts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPm_zero_pts(String newPm_zero_pts)
  {
    String oldPm_zero_pts = pm_zero_pts;
    pm_zero_pts = newPm_zero_pts;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.PERDANTS_MANCHE__PM_ZERO_PTS, oldPm_zero_pts, pm_zero_pts));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPm_pts_selon_cartes_restantes()
  {
    return pm_pts_selon_cartes_restantes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPm_pts_selon_cartes_restantes(String newPm_pts_selon_cartes_restantes)
  {
    String oldPm_pts_selon_cartes_restantes = pm_pts_selon_cartes_restantes;
    pm_pts_selon_cartes_restantes = newPm_pts_selon_cartes_restantes;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.PERDANTS_MANCHE__PM_PTS_SELON_CARTES_RESTANTES, oldPm_pts_selon_cartes_restantes, pm_pts_selon_cartes_restantes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoPackage.PERDANTS_MANCHE__PM_ZERO_PTS:
        return getPm_zero_pts();
      case MyUnoPackage.PERDANTS_MANCHE__PM_PTS_SELON_CARTES_RESTANTES:
        return getPm_pts_selon_cartes_restantes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoPackage.PERDANTS_MANCHE__PM_ZERO_PTS:
        setPm_zero_pts((String)newValue);
        return;
      case MyUnoPackage.PERDANTS_MANCHE__PM_PTS_SELON_CARTES_RESTANTES:
        setPm_pts_selon_cartes_restantes((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.PERDANTS_MANCHE__PM_ZERO_PTS:
        setPm_zero_pts(PM_ZERO_PTS_EDEFAULT);
        return;
      case MyUnoPackage.PERDANTS_MANCHE__PM_PTS_SELON_CARTES_RESTANTES:
        setPm_pts_selon_cartes_restantes(PM_PTS_SELON_CARTES_RESTANTES_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.PERDANTS_MANCHE__PM_ZERO_PTS:
        return PM_ZERO_PTS_EDEFAULT == null ? pm_zero_pts != null : !PM_ZERO_PTS_EDEFAULT.equals(pm_zero_pts);
      case MyUnoPackage.PERDANTS_MANCHE__PM_PTS_SELON_CARTES_RESTANTES:
        return PM_PTS_SELON_CARTES_RESTANTES_EDEFAULT == null ? pm_pts_selon_cartes_restantes != null : !PM_PTS_SELON_CARTES_RESTANTES_EDEFAULT.equals(pm_pts_selon_cartes_restantes);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (pm_zero_pts: ");
    result.append(pm_zero_pts);
    result.append(", pm_pts_selon_cartes_restantes: ");
    result.append(pm_pts_selon_cartes_restantes);
    result.append(')');
    return result.toString();
  }

} //Perdants_mancheImpl
