/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtexthheinle.uno.myUno.Jouer_apres_pioche;
import org.xtexthheinle.uno.myUno.MyUnoPackage;
import org.xtexthheinle.uno.myUno.Nb_cartes_a_piocher;
import org.xtexthheinle.uno.myUno.Pioche;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pioche</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.PiocheImpl#getNb_cartes_a_piocher <em>Nb cartes apiocher</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.PiocheImpl#getJouer_apres_pioche <em>Jouer apres pioche</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PiocheImpl extends MinimalEObjectImpl.Container implements Pioche
{
  /**
   * The default value of the '{@link #getNb_cartes_a_piocher() <em>Nb cartes apiocher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNb_cartes_a_piocher()
   * @generated
   * @ordered
   */
  protected static final Nb_cartes_a_piocher NB_CARTES_APIOCHER_EDEFAULT = Nb_cartes_a_piocher.UNE_SEULE;

  /**
   * The cached value of the '{@link #getNb_cartes_a_piocher() <em>Nb cartes apiocher</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNb_cartes_a_piocher()
   * @generated
   * @ordered
   */
  protected Nb_cartes_a_piocher nb_cartes_a_piocher = NB_CARTES_APIOCHER_EDEFAULT;

  /**
   * The default value of the '{@link #getJouer_apres_pioche() <em>Jouer apres pioche</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJouer_apres_pioche()
   * @generated
   * @ordered
   */
  protected static final Jouer_apres_pioche JOUER_APRES_PIOCHE_EDEFAULT = Jouer_apres_pioche.DROIT_DE_JOUER;

  /**
   * The cached value of the '{@link #getJouer_apres_pioche() <em>Jouer apres pioche</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJouer_apres_pioche()
   * @generated
   * @ordered
   */
  protected Jouer_apres_pioche jouer_apres_pioche = JOUER_APRES_PIOCHE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PiocheImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoPackage.Literals.PIOCHE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Nb_cartes_a_piocher getNb_cartes_a_piocher()
  {
    return nb_cartes_a_piocher;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNb_cartes_a_piocher(Nb_cartes_a_piocher newNb_cartes_a_piocher)
  {
    Nb_cartes_a_piocher oldNb_cartes_a_piocher = nb_cartes_a_piocher;
    nb_cartes_a_piocher = newNb_cartes_a_piocher == null ? NB_CARTES_APIOCHER_EDEFAULT : newNb_cartes_a_piocher;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.PIOCHE__NB_CARTES_APIOCHER, oldNb_cartes_a_piocher, nb_cartes_a_piocher));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Jouer_apres_pioche getJouer_apres_pioche()
  {
    return jouer_apres_pioche;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJouer_apres_pioche(Jouer_apres_pioche newJouer_apres_pioche)
  {
    Jouer_apres_pioche oldJouer_apres_pioche = jouer_apres_pioche;
    jouer_apres_pioche = newJouer_apres_pioche == null ? JOUER_APRES_PIOCHE_EDEFAULT : newJouer_apres_pioche;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.PIOCHE__JOUER_APRES_PIOCHE, oldJouer_apres_pioche, jouer_apres_pioche));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoPackage.PIOCHE__NB_CARTES_APIOCHER:
        return getNb_cartes_a_piocher();
      case MyUnoPackage.PIOCHE__JOUER_APRES_PIOCHE:
        return getJouer_apres_pioche();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoPackage.PIOCHE__NB_CARTES_APIOCHER:
        setNb_cartes_a_piocher((Nb_cartes_a_piocher)newValue);
        return;
      case MyUnoPackage.PIOCHE__JOUER_APRES_PIOCHE:
        setJouer_apres_pioche((Jouer_apres_pioche)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.PIOCHE__NB_CARTES_APIOCHER:
        setNb_cartes_a_piocher(NB_CARTES_APIOCHER_EDEFAULT);
        return;
      case MyUnoPackage.PIOCHE__JOUER_APRES_PIOCHE:
        setJouer_apres_pioche(JOUER_APRES_PIOCHE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.PIOCHE__NB_CARTES_APIOCHER:
        return nb_cartes_a_piocher != NB_CARTES_APIOCHER_EDEFAULT;
      case MyUnoPackage.PIOCHE__JOUER_APRES_PIOCHE:
        return jouer_apres_pioche != JOUER_APRES_PIOCHE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (nb_cartes_a_piocher: ");
    result.append(nb_cartes_a_piocher);
    result.append(", jouer_apres_pioche: ");
    result.append(jouer_apres_pioche);
    result.append(')');
    return result.toString();
  }

} //PiocheImpl
