/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtexthheinle.uno.myUno.MyUnoPackage;
import org.xtexthheinle.uno.myUno.Perdants_manche;
import org.xtexthheinle.uno.myUno.Points_manche;
import org.xtexthheinle.uno.myUno.Vainqueur_manche;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Points manche</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Points_mancheImpl#getVainqueur_manche <em>Vainqueur manche</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Points_mancheImpl#getPerdants_manche <em>Perdants manche</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Points_mancheImpl extends MinimalEObjectImpl.Container implements Points_manche
{
  /**
   * The default value of the '{@link #getVainqueur_manche() <em>Vainqueur manche</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVainqueur_manche()
   * @generated
   * @ordered
   */
  protected static final Vainqueur_manche VAINQUEUR_MANCHE_EDEFAULT = Vainqueur_manche.MANCHE_GAGNEE;

  /**
   * The cached value of the '{@link #getVainqueur_manche() <em>Vainqueur manche</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVainqueur_manche()
   * @generated
   * @ordered
   */
  protected Vainqueur_manche vainqueur_manche = VAINQUEUR_MANCHE_EDEFAULT;

  /**
   * The cached value of the '{@link #getPerdants_manche() <em>Perdants manche</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPerdants_manche()
   * @generated
   * @ordered
   */
  protected Perdants_manche perdants_manche;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Points_mancheImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoPackage.Literals.POINTS_MANCHE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Vainqueur_manche getVainqueur_manche()
  {
    return vainqueur_manche;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVainqueur_manche(Vainqueur_manche newVainqueur_manche)
  {
    Vainqueur_manche oldVainqueur_manche = vainqueur_manche;
    vainqueur_manche = newVainqueur_manche == null ? VAINQUEUR_MANCHE_EDEFAULT : newVainqueur_manche;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.POINTS_MANCHE__VAINQUEUR_MANCHE, oldVainqueur_manche, vainqueur_manche));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Perdants_manche getPerdants_manche()
  {
    return perdants_manche;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPerdants_manche(Perdants_manche newPerdants_manche, NotificationChain msgs)
  {
    Perdants_manche oldPerdants_manche = perdants_manche;
    perdants_manche = newPerdants_manche;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyUnoPackage.POINTS_MANCHE__PERDANTS_MANCHE, oldPerdants_manche, newPerdants_manche);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPerdants_manche(Perdants_manche newPerdants_manche)
  {
    if (newPerdants_manche != perdants_manche)
    {
      NotificationChain msgs = null;
      if (perdants_manche != null)
        msgs = ((InternalEObject)perdants_manche).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyUnoPackage.POINTS_MANCHE__PERDANTS_MANCHE, null, msgs);
      if (newPerdants_manche != null)
        msgs = ((InternalEObject)newPerdants_manche).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyUnoPackage.POINTS_MANCHE__PERDANTS_MANCHE, null, msgs);
      msgs = basicSetPerdants_manche(newPerdants_manche, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.POINTS_MANCHE__PERDANTS_MANCHE, newPerdants_manche, newPerdants_manche));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyUnoPackage.POINTS_MANCHE__PERDANTS_MANCHE:
        return basicSetPerdants_manche(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoPackage.POINTS_MANCHE__VAINQUEUR_MANCHE:
        return getVainqueur_manche();
      case MyUnoPackage.POINTS_MANCHE__PERDANTS_MANCHE:
        return getPerdants_manche();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoPackage.POINTS_MANCHE__VAINQUEUR_MANCHE:
        setVainqueur_manche((Vainqueur_manche)newValue);
        return;
      case MyUnoPackage.POINTS_MANCHE__PERDANTS_MANCHE:
        setPerdants_manche((Perdants_manche)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.POINTS_MANCHE__VAINQUEUR_MANCHE:
        setVainqueur_manche(VAINQUEUR_MANCHE_EDEFAULT);
        return;
      case MyUnoPackage.POINTS_MANCHE__PERDANTS_MANCHE:
        setPerdants_manche((Perdants_manche)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.POINTS_MANCHE__VAINQUEUR_MANCHE:
        return vainqueur_manche != VAINQUEUR_MANCHE_EDEFAULT;
      case MyUnoPackage.POINTS_MANCHE__PERDANTS_MANCHE:
        return perdants_manche != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (vainqueur_manche: ");
    result.append(vainqueur_manche);
    result.append(')');
    return result.toString();
  }

} //Points_mancheImpl
