/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtexthheinle.uno.myUno.MyUnoPackage;
import org.xtexthheinle.uno.myUno.Tourner_les_mains;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Tourner les mains</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Tourner_les_mainsImpl#getAvec_carte_zero <em>Avec carte zero</em>}</li>
 *   <li>{@link org.xtexthheinle.uno.myUno.impl.Tourner_les_mainsImpl#getAvec_carte_uno <em>Avec carte uno</em>}</li>
 * </ul>
 *
 * @generated
 */
public class Tourner_les_mainsImpl extends MinimalEObjectImpl.Container implements Tourner_les_mains
{
  /**
   * The default value of the '{@link #getAvec_carte_zero() <em>Avec carte zero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAvec_carte_zero()
   * @generated
   * @ordered
   */
  protected static final String AVEC_CARTE_ZERO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAvec_carte_zero() <em>Avec carte zero</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAvec_carte_zero()
   * @generated
   * @ordered
   */
  protected String avec_carte_zero = AVEC_CARTE_ZERO_EDEFAULT;

  /**
   * The default value of the '{@link #getAvec_carte_uno() <em>Avec carte uno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAvec_carte_uno()
   * @generated
   * @ordered
   */
  protected static final String AVEC_CARTE_UNO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAvec_carte_uno() <em>Avec carte uno</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAvec_carte_uno()
   * @generated
   * @ordered
   */
  protected String avec_carte_uno = AVEC_CARTE_UNO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Tourner_les_mainsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyUnoPackage.Literals.TOURNER_LES_MAINS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAvec_carte_zero()
  {
    return avec_carte_zero;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAvec_carte_zero(String newAvec_carte_zero)
  {
    String oldAvec_carte_zero = avec_carte_zero;
    avec_carte_zero = newAvec_carte_zero;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.TOURNER_LES_MAINS__AVEC_CARTE_ZERO, oldAvec_carte_zero, avec_carte_zero));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAvec_carte_uno()
  {
    return avec_carte_uno;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAvec_carte_uno(String newAvec_carte_uno)
  {
    String oldAvec_carte_uno = avec_carte_uno;
    avec_carte_uno = newAvec_carte_uno;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyUnoPackage.TOURNER_LES_MAINS__AVEC_CARTE_UNO, oldAvec_carte_uno, avec_carte_uno));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyUnoPackage.TOURNER_LES_MAINS__AVEC_CARTE_ZERO:
        return getAvec_carte_zero();
      case MyUnoPackage.TOURNER_LES_MAINS__AVEC_CARTE_UNO:
        return getAvec_carte_uno();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyUnoPackage.TOURNER_LES_MAINS__AVEC_CARTE_ZERO:
        setAvec_carte_zero((String)newValue);
        return;
      case MyUnoPackage.TOURNER_LES_MAINS__AVEC_CARTE_UNO:
        setAvec_carte_uno((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.TOURNER_LES_MAINS__AVEC_CARTE_ZERO:
        setAvec_carte_zero(AVEC_CARTE_ZERO_EDEFAULT);
        return;
      case MyUnoPackage.TOURNER_LES_MAINS__AVEC_CARTE_UNO:
        setAvec_carte_uno(AVEC_CARTE_UNO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyUnoPackage.TOURNER_LES_MAINS__AVEC_CARTE_ZERO:
        return AVEC_CARTE_ZERO_EDEFAULT == null ? avec_carte_zero != null : !AVEC_CARTE_ZERO_EDEFAULT.equals(avec_carte_zero);
      case MyUnoPackage.TOURNER_LES_MAINS__AVEC_CARTE_UNO:
        return AVEC_CARTE_UNO_EDEFAULT == null ? avec_carte_uno != null : !AVEC_CARTE_UNO_EDEFAULT.equals(avec_carte_uno);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (avec_carte_zero: ");
    result.append(avec_carte_zero);
    result.append(", avec_carte_uno: ");
    result.append(avec_carte_uno);
    result.append(')');
    return result.toString();
  }

} //Tourner_les_mainsImpl
