/**
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.myUno.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtexthheinle.uno.myUno.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtexthheinle.uno.myUno.MyUnoPackage
 * @generated
 */
public class MyUnoSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static MyUnoPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MyUnoSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = MyUnoPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case MyUnoPackage.VARIANTE_UNO:
      {
        Variante_UNO variante_UNO = (Variante_UNO)theEObject;
        T result = caseVariante_UNO(variante_UNO);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.CONFIGURATION_DEPART:
      {
        Configuration_Depart configuration_Depart = (Configuration_Depart)theEObject;
        T result = caseConfiguration_Depart(configuration_Depart);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.MAIN:
      {
        Main main = (Main)theEObject;
        T result = caseMain(main);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.TALON:
      {
        Talon talon = (Talon)theEObject;
        T result = caseTalon(talon);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.MANCHE:
      {
        Manche manche = (Manche)theEObject;
        T result = caseManche(manche);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.INVERSION:
      {
        Inversion inversion = (Inversion)theEObject;
        T result = caseInversion(inversion);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.TOURNER_LES_MAINS:
      {
        Tourner_les_mains tourner_les_mains = (Tourner_les_mains)theEObject;
        T result = caseTourner_les_mains(tourner_les_mains);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.CARTES_19:
      {
        Cartes_1_9 cartes_1_9 = (Cartes_1_9)theEObject;
        T result = caseCartes_1_9(cartes_1_9);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.PIOCHE:
      {
        Pioche pioche = (Pioche)theEObject;
        T result = casePioche(pioche);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.CUMUL:
      {
        Cumul cumul = (Cumul)theEObject;
        T result = caseCumul(cumul);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.CONTESTATIONS:
      {
        Contestations contestations = (Contestations)theEObject;
        T result = caseContestations(contestations);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.FIN_MANCHE:
      {
        Fin_Manche fin_Manche = (Fin_Manche)theEObject;
        T result = caseFin_Manche(fin_Manche);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.POINTS_MANCHE:
      {
        Points_manche points_manche = (Points_manche)theEObject;
        T result = casePoints_manche(points_manche);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.PERDANTS_MANCHE:
      {
        Perdants_manche perdants_manche = (Perdants_manche)theEObject;
        T result = casePerdants_manche(perdants_manche);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case MyUnoPackage.FIN_PARTIE:
      {
        Fin_Partie fin_Partie = (Fin_Partie)theEObject;
        T result = caseFin_Partie(fin_Partie);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Variante UNO</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Variante UNO</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseVariante_UNO(Variante_UNO object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Configuration Depart</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Configuration Depart</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseConfiguration_Depart(Configuration_Depart object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Main</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Main</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseMain(Main object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Talon</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Talon</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTalon(Talon object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Manche</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Manche</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseManche(Manche object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Inversion</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Inversion</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInversion(Inversion object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Tourner les mains</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Tourner les mains</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseTourner_les_mains(Tourner_les_mains object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Cartes 19</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Cartes 19</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCartes_1_9(Cartes_1_9 object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Pioche</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Pioche</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePioche(Pioche object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Cumul</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Cumul</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseCumul(Cumul object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Contestations</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Contestations</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseContestations(Contestations object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Fin Manche</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Fin Manche</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFin_Manche(Fin_Manche object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Points manche</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Points manche</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePoints_manche(Points_manche object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Perdants manche</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Perdants manche</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casePerdants_manche(Perdants_manche object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Fin Partie</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Fin Partie</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFin_Partie(Fin_Partie object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //MyUnoSwitch
