/*
 * generated by Xtext 2.23.0
 */
package org.xtexthheinle.uno.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtexthheinle.uno.services.MyUnoGrammarAccess;

@SuppressWarnings("all")
public class MyUnoSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MyUnoGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Perdants_manche___LeftCurlyBracketKeyword_2_1_0_Elimination_si_500_ptsKeyword_2_1_1_RightCurlyBracketKeyword_2_1_2__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MyUnoGrammarAccess) access;
		match_Perdants_manche___LeftCurlyBracketKeyword_2_1_0_Elimination_si_500_ptsKeyword_2_1_1_RightCurlyBracketKeyword_2_1_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getPerdants_mancheAccess().getLeftCurlyBracketKeyword_2_1_0()), new TokenAlias(false, false, grammarAccess.getPerdants_mancheAccess().getElimination_si_500_ptsKeyword_2_1_1()), new TokenAlias(false, false, grammarAccess.getPerdants_mancheAccess().getRightCurlyBracketKeyword_2_1_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Perdants_manche___LeftCurlyBracketKeyword_2_1_0_Elimination_si_500_ptsKeyword_2_1_1_RightCurlyBracketKeyword_2_1_2__q.equals(syntax))
				emit_Perdants_manche___LeftCurlyBracketKeyword_2_1_0_Elimination_si_500_ptsKeyword_2_1_1_RightCurlyBracketKeyword_2_1_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ('{' 'elimination_si_500_pts' '}')?
	 *
	 * This ambiguous syntax occurs at:
	 *     pm_pts_selon_cartes_restantes='pm_pts_selon_cartes_restantes' (ambiguity) (rule end)
	 */
	protected void emit_Perdants_manche___LeftCurlyBracketKeyword_2_1_0_Elimination_si_500_ptsKeyword_2_1_1_RightCurlyBracketKeyword_2_1_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
